import "IntegratedDynamicsClasses/operators/CurriedOperator";
import "IntegratedDynamicsClasses/operators/PipeOperator";
import "IntegratedDynamicsClasses/operators/Pipe2Operator";
import "IntegratedDynamicsClasses/operators/FlipOperator";
import { OPERATOR_ARITHMETIC_ADDITION } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_ADDITION";
import { OPERATOR_ARITHMETIC_DECREMENT } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_DECREMENT";
import { OPERATOR_ARITHMETIC_DIVISION } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_DIVISION";
import { OPERATOR_ARITHMETIC_INCREMENT } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_INCREMENT";
import { OPERATOR_ARITHMETIC_MAXIMUM } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_MAXIMUM";
import { OPERATOR_ARITHMETIC_MINIMUM } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_MINIMUM";
import { OPERATOR_ARITHMETIC_MODULUS } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_MODULUS";
import { OPERATOR_ARITHMETIC_MULTIPLICATION } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_MULTIPLICATION";
import { OPERATOR_ARITHMETIC_SUBTRACTION } from "IntegratedDynamicsClasses/operators/operators/ARITHMETIC_SUBTRACTION";
import { OPERATOR_BINARY_AND } from "IntegratedDynamicsClasses/operators/operators/BINARY_AND";
import { OPERATOR_BINARY_COMPLEMENT } from "IntegratedDynamicsClasses/operators/operators/BINARY_COMPLEMENT";
import { OPERATOR_BINARY_LSHIFT } from "IntegratedDynamicsClasses/operators/operators/BINARY_LSHIFT";
import { OPERATOR_BINARY_OR } from "IntegratedDynamicsClasses/operators/operators/BINARY_OR";
import { OPERATOR_BINARY_RSHIFT } from "IntegratedDynamicsClasses/operators/operators/BINARY_RSHIFT";
import { OPERATOR_BINARY_XOR } from "IntegratedDynamicsClasses/operators/operators/BINARY_XOR";
import { OPERATOR_DOUBLE_POW } from "IntegratedDynamicsClasses/operators/operators/DOUBLE_POW";
import { OPERATOR_DOUBLE_SQRT } from "IntegratedDynamicsClasses/operators/operators/DOUBLE_SQRT";
import { OPERATOR_DOUBLE_TO_INTEGER } from "IntegratedDynamicsClasses/operators/operators/DOUBLE_TO_INTEGER";
import { OPERATOR_DOUBLE_TO_LONG } from "IntegratedDynamicsClasses/operators/operators/DOUBLE_TO_LONG";
import { OPERATOR_ENTITY_ARMORINVENTORY } from "IntegratedDynamicsClasses/operators/operators/ENTITY_ARMORINVENTORY";
import { OPERATOR_ENTITY_HASGUIOPEN } from "IntegratedDynamicsClasses/operators/operators/ENTITY_HASGUIOPEN";
import { OPERATOR_ENTITY_HEALTH } from "IntegratedDynamicsClasses/operators/operators/ENTITY_HEALTH";
import { OPERATOR_ENTITY_HELDITEM } from "IntegratedDynamicsClasses/operators/operators/ENTITY_HELDITEM";
import { OPERATOR_ENTITY_HELDITEMOFFHAND } from "IntegratedDynamicsClasses/operators/operators/ENTITY_HELDITEMOFFHAND";
import { OPERATOR_ENTITY_ISMINECART } from "IntegratedDynamicsClasses/operators/operators/ENTITY_ISMINECART";
import { OPERATOR_ENTITY_ITEM } from "IntegratedDynamicsClasses/operators/operators/ENTITY_ITEM";
import { OPERATOR_ENTITY_WIDTH } from "IntegratedDynamicsClasses/operators/operators/ENTITY_WIDTH";
import { OPERATOR_GENERAL_CHOICE } from "IntegratedDynamicsClasses/operators/operators/GENERAL_CHOICE";
import { OPERATOR_GENERAL_CONSTANT } from "IntegratedDynamicsClasses/operators/operators/GENERAL_CONSTANT";
import { OPERATOR_GENERAL_IDENTITY } from "IntegratedDynamicsClasses/operators/operators/GENERAL_IDENTITY";
import { OPERATOR_INGREDIENTS_ENERGIES } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_ENERGIES";
import { OPERATOR_INGREDIENTS_FLUIDS } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_FLUIDS";
import { OPERATOR_INGREDIENTS_ITEMS } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_ITEMS";
import { OPERATOR_INGREDIENTS_WITH_ENERGIES } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_WITH_ENERGIES";
import { OPERATOR_INGREDIENTS_WITH_ENERGY } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_WITH_ENERGY";
import { OPERATOR_INGREDIENTS_WITH_FLUID } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_WITH_FLUID";
import { OPERATOR_INGREDIENTS_WITH_FLUIDS } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_WITH_FLUIDS";
import { OPERATOR_INGREDIENTS_WITH_ITEM } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_WITH_ITEM";
import { OPERATOR_INGREDIENTS_WITH_ITEMS } from "IntegratedDynamicsClasses/operators/operators/INGREDIENTS_WITH_ITEMS";
import { OPERATOR_INTEGER_TO_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/INTEGER_TO_DOUBLE";
import { OPERATOR_INTEGER_TO_LONG } from "IntegratedDynamicsClasses/operators/operators/INTEGER_TO_LONG";
import { OPERATOR_ITEMSTACK_CANBURN } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_CANBURN";
import { OPERATOR_ITEMSTACK_DATAVALUE } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_DATAVALUE";
import { OPERATOR_ITEMSTACK_ISFECONTAINER } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_ISFECONTAINER";
import { OPERATOR_ITEMSTACK_ITEMBYNAME } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_ITEMBYNAME";
import { OPERATOR_ITEMSTACK_ITEMLISTCOUNT } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_ITEMLISTCOUNT";
import { OPERATOR_ITEMSTACK_TAG } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_TAG";
import { OPERATOR_ITEMSTACK_TOOLTIP } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_TOOLTIP";
import { OPERATOR_ITEMSTACK_WITH_NBT } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_WITH_NBT";
import { OPERATOR_ITEMSTACK_WITHDATA } from "IntegratedDynamicsClasses/operators/operators/ITEMSTACK_WITHDATA";
import { OPERATOR_LIST_APPEND } from "IntegratedDynamicsClasses/operators/operators/LIST_APPEND";
import { OPERATOR_LIST_CONCAT } from "IntegratedDynamicsClasses/operators/operators/LIST_CONCAT";
import { OPERATOR_LIST_CONTAINS } from "IntegratedDynamicsClasses/operators/operators/LIST_CONTAINS";
import { OPERATOR_LIST_CONTAINS_PREDICATE } from "IntegratedDynamicsClasses/operators/operators/LIST_CONTAINS_PREDICATE";
import { OPERATOR_LIST_COUNT } from "IntegratedDynamicsClasses/operators/operators/LIST_COUNT";
import { OPERATOR_LIST_COUNT_PREDICATE } from "IntegratedDynamicsClasses/operators/operators/LIST_COUNT_PREDICATE";
import { OPERATOR_LIST_ELEMENT } from "IntegratedDynamicsClasses/operators/operators/LIST_ELEMENT";
import { OPERATOR_LIST_ELEMENT_DEFAULT } from "IntegratedDynamicsClasses/operators/operators/LIST_ELEMENT_DEFAULT";
import { OPERATOR_LIST_EMPTY } from "IntegratedDynamicsClasses/operators/operators/LIST_EMPTY";
import { OPERATOR_LIST_EQUALS_MULTISET } from "IntegratedDynamicsClasses/operators/operators/LIST_EQUALS_MULTISET";
import { OPERATOR_LIST_EQUALS_SET } from "IntegratedDynamicsClasses/operators/operators/LIST_EQUALS_SET";
import { OPERATOR_LIST_HEAD } from "IntegratedDynamicsClasses/operators/operators/LIST_HEAD";
import { OPERATOR_LIST_INTERSECTION } from "IntegratedDynamicsClasses/operators/operators/LIST_INTERSECTION";
import { OPERATOR_LIST_LENGTH } from "IntegratedDynamicsClasses/operators/operators/LIST_LENGTH";
import { OPERATOR_LIST_NOT_EMPTY } from "IntegratedDynamicsClasses/operators/operators/LIST_NOT_EMPTY";
import { OPERATOR_LIST_SLICE } from "IntegratedDynamicsClasses/operators/operators/LIST_SLICE";
import { OPERATOR_LIST_TAIL } from "IntegratedDynamicsClasses/operators/operators/LIST_TAIL";
import { OPERATOR_LIST_UNIQ } from "IntegratedDynamicsClasses/operators/operators/LIST_UNIQ";
import { OPERATOR_LIST_UNIQ_PREDICATE } from "IntegratedDynamicsClasses/operators/operators/LIST_UNIQ_PREDICATE";
import { OPERATOR_LOGICAL_AND } from "IntegratedDynamicsClasses/operators/operators/LOGICAL_AND";
import { OPERATOR_LOGICAL_NAND } from "IntegratedDynamicsClasses/operators/operators/LOGICAL_NAND";
import { OPERATOR_LOGICAL_NOR } from "IntegratedDynamicsClasses/operators/operators/LOGICAL_NOR";
import { OPERATOR_LOGICAL_NOT } from "IntegratedDynamicsClasses/operators/operators/LOGICAL_NOT";
import { OPERATOR_LOGICAL_OR } from "IntegratedDynamicsClasses/operators/operators/LOGICAL_OR";
import { OPERATOR_LONG_TO_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/LONG_TO_DOUBLE";
import { OPERATOR_LONG_TO_INTEGER } from "IntegratedDynamicsClasses/operators/operators/LONG_TO_INTEGER";
import { OPERATOR_NAMED_NAME } from "IntegratedDynamicsClasses/operators/operators/NAMED_NAME";
import { OPERATOR_NBT_AS_BOOLEAN } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_BOOLEAN";
import { OPERATOR_NBT_AS_BYTE } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_BYTE";
import { OPERATOR_NBT_AS_BYTE_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_BYTE_LIST";
import { OPERATOR_NBT_AS_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_DOUBLE";
import { OPERATOR_NBT_AS_FLOAT } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_FLOAT";
import { OPERATOR_NBT_AS_INT } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_INT";
import { OPERATOR_NBT_AS_INT_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_INT_LIST";
import { OPERATOR_NBT_AS_LONG } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_LONG";
import { OPERATOR_NBT_AS_LONG_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_LONG_LIST";
import { OPERATOR_NBT_AS_SHORT } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_SHORT";
import { OPERATOR_NBT_AS_STRING } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_STRING";
import { OPERATOR_NBT_AS_TAG_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_AS_TAG_LIST";
import { OPERATOR_NBT_COMPOUND_HASKEY } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_HASKEY";
import { OPERATOR_NBT_COMPOUND_INTERSECTION } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_INTERSECTION";
import { OPERATOR_NBT_COMPOUND_KEYS } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_KEYS";
import { OPERATOR_NBT_COMPOUND_MINUS } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_MINUS";
import { OPERATOR_NBT_COMPOUND_SIZE } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_SIZE";
import { OPERATOR_NBT_COMPOUND_SUBSET } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_SUBSET";
import { OPERATOR_NBT_COMPOUND_UNION } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_UNION";
import { OPERATOR_NBT_COMPOUND_VALUE_BOOLEAN } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_BOOLEAN";
import { OPERATOR_NBT_COMPOUND_VALUE_COMPOUND } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_COMPOUND";
import { OPERATOR_NBT_COMPOUND_VALUE_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_DOUBLE";
import { OPERATOR_NBT_COMPOUND_VALUE_INTEGER } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_INTEGER";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_BYTE } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_LIST_BYTE";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_INT } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_LIST_INT";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_LONG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_LIST_LONG";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_TAG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_LIST_TAG";
import { OPERATOR_NBT_COMPOUND_VALUE_LONG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_LONG";
import { OPERATOR_NBT_COMPOUND_VALUE_STRING } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_STRING";
import { OPERATOR_NBT_COMPOUND_VALUE_TAG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_TAG";
import { OPERATOR_NBT_COMPOUND_VALUE_TYPE } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_VALUE_TYPE";
import { OPERATOR_NBT_COMPOUND_WITH_BOOLEAN } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_BOOLEAN";
import { OPERATOR_NBT_COMPOUND_WITH_COMPOUND } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_COMPOUND";
import { OPERATOR_NBT_COMPOUND_WITH_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_DOUBLE";
import { OPERATOR_NBT_COMPOUND_WITH_FLOAT } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_FLOAT";
import { OPERATOR_NBT_COMPOUND_WITH_INTEGER } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_INTEGER";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_BYTE } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_LIST_BYTE";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_INT } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_LIST_INT";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_LONG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_LIST_LONG";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_TAG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_LIST_TAG";
import { OPERATOR_NBT_COMPOUND_WITH_LONG } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_LONG";
import { OPERATOR_NBT_COMPOUND_WITH_SHORT } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_SHORT";
import { OPERATOR_NBT_COMPOUND_WITH_STRING } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITH_STRING";
import { OPERATOR_NBT_COMPOUND_WITHOUT } from "IntegratedDynamicsClasses/operators/operators/NBT_COMPOUND_WITHOUT";
import { OPERATOR_NBT_FROM_BOOLEAN } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_BOOLEAN";
import { OPERATOR_NBT_FROM_BYTE } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_BYTE";
import { OPERATOR_NBT_FROM_BYTE_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_BYTE_LIST";
import { OPERATOR_NBT_FROM_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_DOUBLE";
import { OPERATOR_NBT_FROM_FLOAT } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_FLOAT";
import { OPERATOR_NBT_FROM_INT } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_INT";
import { OPERATOR_NBT_FROM_INT_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_INT_LIST";
import { OPERATOR_NBT_FROM_LONG } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_LONG";
import { OPERATOR_NBT_FROM_LONG_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_LONG_LIST";
import { OPERATOR_NBT_FROM_SHORT } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_SHORT";
import { OPERATOR_NBT_FROM_STRING } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_STRING";
import { OPERATOR_NBT_FROM_TAG_LIST } from "IntegratedDynamicsClasses/operators/operators/NBT_FROM_TAG_LIST";
import { OPERATOR_NBT_PATH_MATCH_ALL } from "IntegratedDynamicsClasses/operators/operators/NBT_PATH_MATCH_ALL";
import { OPERATOR_NBT_PATH_MATCH_FIRST } from "IntegratedDynamicsClasses/operators/operators/NBT_PATH_MATCH_FIRST";
import { OPERATOR_NBT_PATH_TEST } from "IntegratedDynamicsClasses/operators/operators/NBT_PATH_TEST";
import { OPERATOR_NULLABLE_ISNOTNULL } from "IntegratedDynamicsClasses/operators/operators/NULLABLE_ISNOTNULL";
import { OPERATOR_NULLABLE_ISNULL } from "IntegratedDynamicsClasses/operators/operators/NULLABLE_ISNULL";
import { OPERATOR_NUMBER_CEIL } from "IntegratedDynamicsClasses/operators/operators/NUMBER_CEIL";
import { OPERATOR_NUMBER_COMPACT } from "IntegratedDynamicsClasses/operators/operators/NUMBER_COMPACT";
import { OPERATOR_NUMBER_FLOOR } from "IntegratedDynamicsClasses/operators/operators/NUMBER_FLOOR";
import { OPERATOR_NUMBER_ROUND } from "IntegratedDynamicsClasses/operators/operators/NUMBER_ROUND";
import { OPERATOR_OBJECT_BLOCK_BREAKSOUND } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_BREAKSOUND";
import { OPERATOR_OBJECT_BLOCK_BY_NAME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_BY_NAME";
import { OPERATOR_OBJECT_BLOCK_ISSHEARABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_ISSHEARABLE";
import { OPERATOR_OBJECT_BLOCK_ISPLANTABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_ISPLANTABLE";
import { OPERATOR_OBJECT_BLOCK_ITEMSTACK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_ITEMSTACK";
import { OPERATOR_OBJECT_BLOCK_MODNAME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_MODNAME";
import { OPERATOR_OBJECT_BLOCK_OPAQUE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_OPAQUE";
import { OPERATOR_OBJECT_BLOCK_PLACESOUND } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_PLACESOUND";
import { OPERATOR_OBJECT_BLOCK_PLANT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_PLANT";
import { OPERATOR_OBJECT_BLOCK_PLANTAGE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_PLANTAGE";
import { OPERATOR_OBJECT_BLOCK_PLANTTYPE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_PLANTTYPE";
import { OPERATOR_OBJECT_BLOCK_POSSIBLE_PROPERTIES } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_POSSIBLE_PROPERTIES";
import { OPERATOR_OBJECT_BLOCK_PROPERTIES } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_PROPERTIES";
import { OPERATOR_OBJECT_BLOCK_STEPSOUND } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_STEPSOUND";
import { OPERATOR_OBJECT_BLOCK_TAG } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_TAG";
import { OPERATOR_OBJECT_BLOCK_TAG_STACKS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_TAG_STACKS";
import { OPERATOR_OBJECT_BLOCK_WITH_PROPERTIES } from "IntegratedDynamicsClasses/operators/operators/OBJECT_BLOCK_WITH_PROPERTIES";
import { OPERATOR_OBJECT_ENTITY_AGE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_AGE";
import { OPERATOR_OBJECT_ENTITY_CANBREED } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_CANBREED";
import { OPERATOR_OBJECT_ENTITY_CANBREEDWITH } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_CANBREEDWITH";
import { OPERATOR_OBJECT_ENTITY_DEATHSOUND } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_DEATHSOUND";
import { OPERATOR_OBJECT_ENTITY_ENERGY_CAPACITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ENERGY_CAPACITY";
import { OPERATOR_OBJECT_ENTITY_ENERGY_STORED } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ENERGY_STORED";
import { OPERATOR_OBJECT_ENTITY_ENTITYITEMTOOLTIP } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ENTITYITEMTOOLTIP";
import { OPERATOR_OBJECT_ENTITY_FLUIDS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_FLUIDS";
import { OPERATOR_OBJECT_ENTITY_HEIGHT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_HEIGHT";
import { OPERATOR_OBJECT_ENTITY_HURTSOUND } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_HURTSOUND";
import { OPERATOR_OBJECT_ENTITY_INVENTORY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_INVENTORY";
import { OPERATOR_OBJECT_ENTITY_ISANIMAL } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISANIMAL";
import { OPERATOR_OBJECT_ENTITY_ISBURNING } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISBURNING";
import { OPERATOR_OBJECT_ENTITY_ISCHILD } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISCHILD";
import { OPERATOR_OBJECT_ENTITY_ISCROUCHING } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISCROUCHING";
import { OPERATOR_OBJECT_ENTITY_ISEATING } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISEATING";
import { OPERATOR_OBJECT_ENTITY_ISINLOVE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISINLOVE";
import { OPERATOR_OBJECT_ENTITY_ISITEM } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISITEM";
import { OPERATOR_OBJECT_ENTITY_ISMOB } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISMOB";
import { OPERATOR_OBJECT_ENTITY_ISPLAYER } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISPLAYER";
import { OPERATOR_OBJECT_ENTITY_ISSHEARABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISSHEARABLE";
import { OPERATOR_OBJECT_ENTITY_ISWET } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ISWET";
import { OPERATOR_OBJECT_ENTITY_ITEMS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_ITEMS";
import { OPERATOR_OBJECT_ENTITY_MODNAME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_MODNAME";
import { OPERATOR_OBJECT_ENTITY_MOUNTED } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_MOUNTED";
import { OPERATOR_OBJECT_ENTITY_NBT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_NBT";
import { OPERATOR_OBJECT_ENTITY_TYPE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_TYPE";
import { OPERATOR_OBJECT_ENTITY_WIDTH } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ENTITY_WIDTH";
import { OPERATOR_OBJECT_FLUIDSTACK_AMOUNT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_AMOUNT";
import { OPERATOR_OBJECT_FLUIDSTACK_BLOCK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_BLOCK";
import { OPERATOR_OBJECT_FLUIDSTACK_BUCKET } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_BUCKET";
import { OPERATOR_OBJECT_FLUIDSTACK_BY_NAME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_BY_NAME";
import { OPERATOR_OBJECT_FLUIDSTACK_DATA } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_DATA";
import { OPERATOR_OBJECT_FLUIDSTACK_DATA_VALUE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_DATA_VALUE";
import { OPERATOR_OBJECT_FLUIDSTACK_DATAKEYS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_DATAKEYS";
import { OPERATOR_OBJECT_FLUIDSTACK_DENSITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_DENSITY";
import { OPERATOR_OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR";
import { OPERATOR_OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL";
import { OPERATOR_OBJECT_FLUIDSTACK_LIGHT_LEVEL } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_LIGHT_LEVEL";
import { OPERATOR_OBJECT_FLUIDSTACK_MODNAME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_MODNAME";
import { OPERATOR_OBJECT_FLUIDSTACK_RARITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_RARITY";
import { OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY";
import { OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL";
import { OPERATOR_OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE";
import { OPERATOR_OBJECT_FLUIDSTACK_TAG } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_TAG";
import { OPERATOR_OBJECT_FLUIDSTACK_TAG_STACKS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_TAG_STACKS";
import { OPERATOR_OBJECT_FLUIDSTACK_TEMPERATURE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_TEMPERATURE";
import { OPERATOR_OBJECT_FLUIDSTACK_VISCOSITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_VISCOSITY";
import { OPERATOR_OBJECT_FLUIDSTACK_WITH_AMOUNT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_WITH_AMOUNT";
import { OPERATOR_OBJECT_FLUIDSTACK_WITH_DATA } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_WITH_DATA";
import { OPERATOR_OBJECT_FLUIDSTACK_WITH_NBT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_FLUIDSTACK_WITH_NBT";
import { OPERATOR_OBJECT_ITEMFRAME_CONTENTS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMFRAME_CONTENTS";
import { OPERATOR_OBJECT_ITEMFRAME_ROTATION } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMFRAME_ROTATION";
import { OPERATOR_OBJECT_ITEMSTACK_BLOCK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_BLOCK";
import { OPERATOR_OBJECT_ITEMSTACK_CANHARVESTBLOCK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_CANHARVESTBLOCK";
import { OPERATOR_OBJECT_ITEMSTACK_DAMAGE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_DAMAGE";
import { OPERATOR_OBJECT_ITEMSTACK_DATA_KEYS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_DATA_KEYS";
import { OPERATOR_OBJECT_ITEMSTACK_FE_CAPACITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_FE_CAPACITY";
import { OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_FLUIDSTACK";
import { OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY";
import { OPERATOR_OBJECT_ITEMSTACK_FUELBURNTIME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_FUELBURNTIME";
import { OPERATOR_OBJECT_ITEMSTACK_HASINVENTORY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_HASINVENTORY";
import { OPERATOR_OBJECT_ITEMSTACK_HASNBT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_HASNBT";
import { OPERATOR_OBJECT_ITEMSTACK_INVENTORY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_INVENTORY";
import { OPERATOR_OBJECT_ITEMSTACK_INVENTORYSIZE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_INVENTORYSIZE";
import { OPERATOR_OBJECT_ITEMSTACK_ISDAMAGEABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISDAMAGEABLE";
import { OPERATOR_OBJECT_ITEMSTACK_ISDATAEQUAL } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISDATAEQUAL";
import { OPERATOR_OBJECT_ITEMSTACK_ISENCHANTABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISENCHANTABLE";
import { OPERATOR_OBJECT_ITEMSTACK_ISENCHANTED } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISENCHANTED";
import { OPERATOR_OBJECT_ITEMSTACK_ISPLANTABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISPLANTABLE";
import { OPERATOR_OBJECT_ITEMSTACK_ISFLUIDSTACK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISFLUIDSTACK";
import { OPERATOR_OBJECT_ITEMSTACK_ISITEMEQUALNODATA } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISITEMEQUALNODATA";
import { OPERATOR_OBJECT_ITEMSTACK_ISRAWITEMEQUAL } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISRAWITEMEQUAL";
import { OPERATOR_OBJECT_ITEMSTACK_ISSTACKABLE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_ISSTACKABLE";
import { OPERATOR_OBJECT_ITEMSTACK_MAXDAMAGE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_MAXDAMAGE";
import { OPERATOR_OBJECT_ITEMSTACK_MAXSIZE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_MAXSIZE";
import { OPERATOR_OBJECT_ITEMSTACK_MODNAME } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_MODNAME";
import { OPERATOR_OBJECT_ITEMSTACK_NBT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_NBT";
import { OPERATOR_OBJECT_ITEMSTACK_PLANT } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_PLANT";
import { OPERATOR_OBJECT_ITEMSTACK_PLANTTYPE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_PLANTTYPE";
import { OPERATOR_OBJECT_ITEMSTACK_RARITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_RARITY";
import { OPERATOR_OBJECT_ITEMSTACK_REPAIRCOST } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_REPAIRCOST";
import { OPERATOR_OBJECT_ITEMSTACK_SIZE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_SIZE";
import { OPERATOR_OBJECT_ITEMSTACK_STORED_FE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_STORED_FE";
import { OPERATOR_OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK";
import { OPERATOR_OBJECT_ITEMSTACK_TAG } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_TAG";
import { OPERATOR_OBJECT_ITEMSTACK_TAG_STACKS } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_TAG_STACKS";
import { OPERATOR_OBJECT_ITEMSTACK_WITHSIZE } from "IntegratedDynamicsClasses/operators/operators/OBJECT_ITEMSTACK_WITHSIZE";
import { OPERATOR_OBJECT_PLAYER_TARGETBLOCK } from "IntegratedDynamicsClasses/operators/operators/OBJECT_PLAYER_TARGETBLOCK";
import { OPERATOR_OBJECT_PLAYER_TARGETENTITY } from "IntegratedDynamicsClasses/operators/operators/OBJECT_PLAYER_TARGETENTITY";
import { OPERATOR_OPERATOR_APPLY } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_APPLY";
import { OPERATOR_OPERATOR_APPLY_0 } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_APPLY_0";
import { OPERATOR_OPERATOR_APPLY_2 } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_APPLY_2";
import { OPERATOR_OPERATOR_APPLY_3 } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_APPLY_3";
import { OPERATOR_OPERATOR_APPLY_N } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_APPLY_N";
import { OPERATOR_OPERATOR_BY_NAME } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_BY_NAME";
import { OPERATOR_OPERATOR_CONJUNCTION } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_CONJUNCTION";
import { OPERATOR_OPERATOR_DISJUNCTION } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_DISJUNCTION";
import { OPERATOR_OPERATOR_FILTER } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_FILTER";
import { OPERATOR_OPERATOR_FLIP } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_FLIP";
import { OPERATOR_OPERATOR_MAP } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_MAP";
import { OPERATOR_OPERATOR_NEGATION } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_NEGATION";
import { OPERATOR_OPERATOR_PIPE } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_PIPE";
import { OPERATOR_OPERATOR_PIPE2 } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_PIPE2";
import { OPERATOR_OPERATOR_REDUCE } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_REDUCE";
import { OPERATOR_OPERATOR_REDUCE1 } from "IntegratedDynamicsClasses/operators/operators/OPERATOR_REDUCE1";
import { OPERATOR_PARSE_BOOLEAN } from "IntegratedDynamicsClasses/operators/operators/PARSE_BOOLEAN";
import { OPERATOR_PARSE_DOUBLE } from "IntegratedDynamicsClasses/operators/operators/PARSE_DOUBLE";
import { OPERATOR_PARSE_INTEGER } from "IntegratedDynamicsClasses/operators/operators/PARSE_INTEGER";
import { OPERATOR_PARSE_LONG } from "IntegratedDynamicsClasses/operators/operators/PARSE_LONG";
import { OPERATOR_PARSE_NBT } from "IntegratedDynamicsClasses/operators/operators/PARSE_NBT";
import { OPERATOR_RECIPE_INPUT } from "IntegratedDynamicsClasses/operators/operators/RECIPE_INPUT";
import { OPERATOR_RECIPE_OUTPUT } from "IntegratedDynamicsClasses/operators/operators/RECIPE_OUTPUT";
import { OPERATOR_RECIPE_WITH_INPUT } from "IntegratedDynamicsClasses/operators/operators/RECIPE_WITH_INPUT";
import { OPERATOR_RECIPE_WITH_INPUT_OUTPUT } from "IntegratedDynamicsClasses/operators/operators/RECIPE_WITH_INPUT_OUTPUT";
import { OPERATOR_RECIPE_WITH_OUTPUT } from "IntegratedDynamicsClasses/operators/operators/RECIPE_WITH_OUTPUT";
import { OPERATOR_RELATIONAL_EQUALS } from "IntegratedDynamicsClasses/operators/operators/RELATIONAL_EQUALS";
import { OPERATOR_RELATIONAL_GE } from "IntegratedDynamicsClasses/operators/operators/RELATIONAL_GE";
import { OPERATOR_RELATIONAL_GT } from "IntegratedDynamicsClasses/operators/operators/RELATIONAL_GT";
import { OPERATOR_RELATIONAL_LE } from "IntegratedDynamicsClasses/operators/operators/RELATIONAL_LE";
import { OPERATOR_RELATIONAL_LT } from "IntegratedDynamicsClasses/operators/operators/RELATIONAL_LT";
import { OPERATOR_RELATIONAL_NOTEQUALS } from "IntegratedDynamicsClasses/operators/operators/RELATIONAL_NOTEQUALS";
import { OPERATOR_STRING_CONCAT } from "IntegratedDynamicsClasses/operators/operators/STRING_CONCAT";
import { OPERATOR_STRING_CONTAINS } from "IntegratedDynamicsClasses/operators/operators/STRING_CONTAINS";
import { OPERATOR_STRING_CONTAINS_REGEX } from "IntegratedDynamicsClasses/operators/operators/STRING_CONTAINS_REGEX";
import { OPERATOR_STRING_ENDS_WITH } from "IntegratedDynamicsClasses/operators/operators/STRING_ENDS_WITH";
import { OPERATOR_STRING_ERROR } from "IntegratedDynamicsClasses/operators/operators/STRING_ERROR";
import { OPERATOR_STRING_INDEX_OF } from "IntegratedDynamicsClasses/operators/operators/STRING_INDEX_OF";
import { OPERATOR_STRING_INDEX_OF_REGEX } from "IntegratedDynamicsClasses/operators/operators/STRING_INDEX_OF_REGEX";
import { OPERATOR_STRING_JOIN } from "IntegratedDynamicsClasses/operators/operators/STRING_JOIN";
import { OPERATOR_STRING_LENGTH } from "IntegratedDynamicsClasses/operators/operators/STRING_LENGTH";
import { OPERATOR_STRING_MATCHES_REGEX } from "IntegratedDynamicsClasses/operators/operators/STRING_MATCHES_REGEX";
import { OPERATOR_STRING_REGEX_GROUP } from "IntegratedDynamicsClasses/operators/operators/STRING_REGEX_GROUP";
import { OPERATOR_STRING_REGEX_GROUPS } from "IntegratedDynamicsClasses/operators/operators/STRING_REGEX_GROUPS";
import { OPERATOR_STRING_REGEX_SCAN } from "IntegratedDynamicsClasses/operators/operators/STRING_REGEX_SCAN";
import { OPERATOR_STRING_REPLACE } from "IntegratedDynamicsClasses/operators/operators/STRING_REPLACE";
import { OPERATOR_STRING_REPLACE_REGEX } from "IntegratedDynamicsClasses/operators/operators/STRING_REPLACE_REGEX";
import { OPERATOR_STRING_SPLIT_ON } from "IntegratedDynamicsClasses/operators/operators/STRING_SPLIT_ON";
import { OPERATOR_STRING_SPLIT_ON_REGEX } from "IntegratedDynamicsClasses/operators/operators/STRING_SPLIT_ON_REGEX";
import { OPERATOR_STRING_STARTS_WITH } from "IntegratedDynamicsClasses/operators/operators/STRING_STARTS_WITH";
import { OPERATOR_STRING_SUBSTRING } from "IntegratedDynamicsClasses/operators/operators/STRING_SUBSTRING";
import { OPERATOR_STRING_TAG } from "IntegratedDynamicsClasses/operators/operators/STRING_TAG";
import { OPERATOR_UNIQUELY_NAMED_UNIQUE_NAME } from "IntegratedDynamicsClasses/operators/operators/UNIQUELY_NAMED_UNIQUE_NAME";
import { OPERATOR_BINARY_RZSHIFT } from "IntegratedDynamicsClasses/operators/operators/BINARY_RZSHIFT";
import { OPERATOR_LIST_LAZYBUILT } from "IntegratedDynamicsClasses/operators/operators/LIST_LAZYBUILT";
import { BaseOperator } from "IntegratedDynamicsClasses/operators/BaseOperator";
import { RegistryHub } from "./registryHub";

const operatorRegistryClass = class operatorRegistryClass {
  constructor() {}

  find(uname: string): BaseOperator<IntegratedValue, IntegratedValue> | void {
    for (const value of Object.values(this)) {
      if (value.name === "find") continue;
      const internalName = value.internalName;
      if (internalName === uname) return new value();
    }
  }

  operatorByNickname(nickname: string): TypeOperatorKey | void {
    for (const [key, opClass] of Object.entries(this)) {
      if (key === "find" || key === "operatorByNickname") continue;
      if (typeof opClass === "function") {
        const staticOp = opClass as typeof BaseOperator;
        if (staticOp.internalName === nickname) return key as TypeOperatorKey;

        if (key === nickname) return key as TypeOperatorKey;

        if (staticOp.nicknames.includes(nickname))
          return key as TypeOperatorKey;
      }
    }
  }

  LOGICAL_AND = OPERATOR_LOGICAL_AND;
  LOGICAL_OR = OPERATOR_LOGICAL_OR;
  LOGICAL_NOT = OPERATOR_LOGICAL_NOT;
  LOGICAL_NAND = OPERATOR_LOGICAL_NAND;
  LOGICAL_NOR = OPERATOR_LOGICAL_NOR;
  ARITHMETIC_ADDITION = OPERATOR_ARITHMETIC_ADDITION;
  ARITHMETIC_SUBTRACTION = OPERATOR_ARITHMETIC_SUBTRACTION;
  ARITHMETIC_MULTIPLICATION = OPERATOR_ARITHMETIC_MULTIPLICATION;
  ARITHMETIC_DIVISION = OPERATOR_ARITHMETIC_DIVISION;
  ARITHMETIC_MAXIMUM = OPERATOR_ARITHMETIC_MAXIMUM;
  ARITHMETIC_MINIMUM = OPERATOR_ARITHMETIC_MINIMUM;
  ARITHMETIC_INCREMENT = OPERATOR_ARITHMETIC_INCREMENT;
  ARITHMETIC_DECREMENT = OPERATOR_ARITHMETIC_DECREMENT;
  ARITHMETIC_MODULUS = OPERATOR_ARITHMETIC_MODULUS;
  DOUBLE_SQRT = OPERATOR_DOUBLE_SQRT;
  DOUBLE_POW = OPERATOR_DOUBLE_POW;
  RELATIONAL_EQUALS = OPERATOR_RELATIONAL_EQUALS;
  RELATIONAL_GT = OPERATOR_RELATIONAL_GT;
  RELATIONAL_LT = OPERATOR_RELATIONAL_LT;
  RELATIONAL_NOTEQUALS = OPERATOR_RELATIONAL_NOTEQUALS;
  RELATIONAL_GE = OPERATOR_RELATIONAL_GE;
  RELATIONAL_LE = OPERATOR_RELATIONAL_LE;
  BINARY_AND = OPERATOR_BINARY_AND;
  BINARY_OR = OPERATOR_BINARY_OR;
  BINARY_XOR = OPERATOR_BINARY_XOR;
  BINARY_COMPLEMENT = OPERATOR_BINARY_COMPLEMENT;
  BINARY_LSHIFT = OPERATOR_BINARY_LSHIFT;
  BINARY_RSHIFT = OPERATOR_BINARY_RSHIFT;
  BINARY_RZSHIFT = OPERATOR_BINARY_RZSHIFT;
  STRING_LENGTH = OPERATOR_STRING_LENGTH;
  STRING_CONCAT = OPERATOR_STRING_CONCAT;
  STRING_CONTAINS = OPERATOR_STRING_CONTAINS;
  STRING_CONTAINS_REGEX = OPERATOR_STRING_CONTAINS_REGEX;
  STRING_MATCHES_REGEX = OPERATOR_STRING_MATCHES_REGEX;
  STRING_INDEX_OF = OPERATOR_STRING_INDEX_OF;
  STRING_INDEX_OF_REGEX = OPERATOR_STRING_INDEX_OF_REGEX;
  STRING_STARTS_WITH = OPERATOR_STRING_STARTS_WITH;
  STRING_ENDS_WITH = OPERATOR_STRING_ENDS_WITH;
  STRING_SPLIT_ON = OPERATOR_STRING_SPLIT_ON;
  STRING_SPLIT_ON_REGEX = OPERATOR_STRING_SPLIT_ON_REGEX;
  STRING_SUBSTRING = OPERATOR_STRING_SUBSTRING;
  STRING_REGEX_GROUP = OPERATOR_STRING_REGEX_GROUP;
  STRING_REGEX_GROUPS = OPERATOR_STRING_REGEX_GROUPS;
  STRING_REGEX_SCAN = OPERATOR_STRING_REGEX_SCAN;
  STRING_REPLACE = OPERATOR_STRING_REPLACE;
  STRING_REPLACE_REGEX = OPERATOR_STRING_REPLACE_REGEX;
  STRING_JOIN = OPERATOR_STRING_JOIN;
  NAMED_NAME = OPERATOR_NAMED_NAME;
  UNIQUELY_NAMED_UNIQUE_NAME = OPERATOR_UNIQUELY_NAMED_UNIQUE_NAME;
  STRING_ERROR = OPERATOR_STRING_ERROR;
  NUMBER_ROUND = OPERATOR_NUMBER_ROUND;
  NUMBER_CEIL = OPERATOR_NUMBER_CEIL;
  NUMBER_FLOOR = OPERATOR_NUMBER_FLOOR;
  NUMBER_COMPACT = OPERATOR_NUMBER_COMPACT;
  NULLABLE_ISNULL = OPERATOR_NULLABLE_ISNULL;
  NULLABLE_ISNOTNULL = OPERATOR_NULLABLE_ISNOTNULL;
  LIST_LENGTH = OPERATOR_LIST_LENGTH;
  LIST_EMPTY = OPERATOR_LIST_EMPTY;
  LIST_NOT_EMPTY = OPERATOR_LIST_NOT_EMPTY;
  LIST_ELEMENT = OPERATOR_LIST_ELEMENT;
  LIST_ELEMENT_DEFAULT = OPERATOR_LIST_ELEMENT_DEFAULT;
  LIST_CONTAINS = OPERATOR_LIST_CONTAINS;
  LIST_CONTAINS_PREDICATE = OPERATOR_LIST_CONTAINS_PREDICATE;
  LIST_COUNT = OPERATOR_LIST_COUNT;
  LIST_COUNT_PREDICATE = OPERATOR_LIST_COUNT_PREDICATE;
  LIST_APPEND = OPERATOR_LIST_APPEND;
  LIST_CONCAT = OPERATOR_LIST_CONCAT;
  LIST_LAZYBUILT = OPERATOR_LIST_LAZYBUILT;
  LIST_HEAD = OPERATOR_LIST_HEAD;
  LIST_TAIL = OPERATOR_LIST_TAIL;
  LIST_UNIQ_PREDICATE = OPERATOR_LIST_UNIQ_PREDICATE;
  LIST_UNIQ = OPERATOR_LIST_UNIQ;
  LIST_SLICE = OPERATOR_LIST_SLICE;
  LIST_INTERSECTION = OPERATOR_LIST_INTERSECTION;
  LIST_EQUALS_SET = OPERATOR_LIST_EQUALS_SET;
  LIST_EQUALS_MULTISET = OPERATOR_LIST_EQUALS_MULTISET;
  OBJECT_BLOCK_OPAQUE = OPERATOR_OBJECT_BLOCK_OPAQUE;
  OBJECT_BLOCK_ITEMSTACK = OPERATOR_OBJECT_BLOCK_ITEMSTACK;
  OBJECT_BLOCK_MODNAME = OPERATOR_OBJECT_BLOCK_MODNAME;
  OBJECT_BLOCK_BREAKSOUND = OPERATOR_OBJECT_BLOCK_BREAKSOUND;
  OBJECT_BLOCK_PLACESOUND = OPERATOR_OBJECT_BLOCK_PLACESOUND;
  OBJECT_BLOCK_STEPSOUND = OPERATOR_OBJECT_BLOCK_STEPSOUND;
  OBJECT_BLOCK_ISSHEARABLE = OPERATOR_OBJECT_BLOCK_ISSHEARABLE;
  OBJECT_BLOCK_ISPLANTABLE = OPERATOR_OBJECT_BLOCK_ISPLANTABLE;
  OBJECT_BLOCK_PLANT = OPERATOR_OBJECT_BLOCK_PLANT;
  OBJECT_BLOCK_PLANTAGE = OPERATOR_OBJECT_BLOCK_PLANTAGE;
  OBJECT_BLOCK_PLANTTYPE = OPERATOR_OBJECT_BLOCK_PLANTTYPE;
  OBJECT_BLOCK_BY_NAME = OPERATOR_OBJECT_BLOCK_BY_NAME;
  OBJECT_BLOCK_PROPERTIES = OPERATOR_OBJECT_BLOCK_PROPERTIES;
  OBJECT_BLOCK_WITH_PROPERTIES = OPERATOR_OBJECT_BLOCK_WITH_PROPERTIES;
  OBJECT_BLOCK_POSSIBLE_PROPERTIES = OPERATOR_OBJECT_BLOCK_POSSIBLE_PROPERTIES;
  OBJECT_BLOCK_TAG = OPERATOR_OBJECT_BLOCK_TAG;
  OBJECT_BLOCK_TAG_STACKS = OPERATOR_OBJECT_BLOCK_TAG_STACKS;
  OBJECT_ITEMSTACK_SIZE = OPERATOR_OBJECT_ITEMSTACK_SIZE;
  OBJECT_ITEMSTACK_MAXSIZE = OPERATOR_OBJECT_ITEMSTACK_MAXSIZE;
  OBJECT_ITEMSTACK_ISSTACKABLE = OPERATOR_OBJECT_ITEMSTACK_ISSTACKABLE;
  OBJECT_ITEMSTACK_ISDAMAGEABLE = OPERATOR_OBJECT_ITEMSTACK_ISDAMAGEABLE;
  OBJECT_ITEMSTACK_DAMAGE = OPERATOR_OBJECT_ITEMSTACK_DAMAGE;
  OBJECT_ITEMSTACK_MAXDAMAGE = OPERATOR_OBJECT_ITEMSTACK_MAXDAMAGE;
  OBJECT_ITEMSTACK_ISENCHANTED = OPERATOR_OBJECT_ITEMSTACK_ISENCHANTED;
  OBJECT_ITEMSTACK_ISPLANTABLE = OPERATOR_OBJECT_ITEMSTACK_ISPLANTABLE;
  OBJECT_ITEMSTACK_ISENCHANTABLE = OPERATOR_OBJECT_ITEMSTACK_ISENCHANTABLE;
  OBJECT_ITEMSTACK_REPAIRCOST = OPERATOR_OBJECT_ITEMSTACK_REPAIRCOST;
  OBJECT_ITEMSTACK_RARITY = OPERATOR_OBJECT_ITEMSTACK_RARITY;
  OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK =
    OPERATOR_OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK;
  OBJECT_ITEMSTACK_CANHARVESTBLOCK = OPERATOR_OBJECT_ITEMSTACK_CANHARVESTBLOCK;
  OBJECT_ITEMSTACK_BLOCK = OPERATOR_OBJECT_ITEMSTACK_BLOCK;
  OBJECT_ITEMSTACK_ISFLUIDSTACK = OPERATOR_OBJECT_ITEMSTACK_ISFLUIDSTACK;
  OBJECT_ITEMSTACK_FLUIDSTACK = OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACK;
  OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY =
    OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY;
  OBJECT_ITEMSTACK_ISDATAEQUAL = OPERATOR_OBJECT_ITEMSTACK_ISDATAEQUAL;
  OBJECT_ITEMSTACK_ISITEMEQUALNODATA =
    OPERATOR_OBJECT_ITEMSTACK_ISITEMEQUALNODATA;
  OBJECT_ITEMSTACK_ISRAWITEMEQUAL = OPERATOR_OBJECT_ITEMSTACK_ISRAWITEMEQUAL;
  OBJECT_ITEMSTACK_MODNAME = OPERATOR_OBJECT_ITEMSTACK_MODNAME;
  OBJECT_ITEMSTACK_FUELBURNTIME = OPERATOR_OBJECT_ITEMSTACK_FUELBURNTIME;
  ITEMSTACK_CANBURN = OPERATOR_ITEMSTACK_CANBURN;
  ITEMSTACK_TAG = OPERATOR_ITEMSTACK_TAG;
  STRING_TAG = OPERATOR_STRING_TAG;
  OBJECT_ITEMSTACK_TAG_STACKS = OPERATOR_OBJECT_ITEMSTACK_TAG_STACKS;
  OBJECT_ITEMSTACK_WITHSIZE = OPERATOR_OBJECT_ITEMSTACK_WITHSIZE;
  ITEMSTACK_ISFECONTAINER = OPERATOR_ITEMSTACK_ISFECONTAINER;
  OBJECT_ITEMSTACK_STORED_FE = OPERATOR_OBJECT_ITEMSTACK_STORED_FE;
  OBJECT_ITEMSTACK_FE_CAPACITY = OPERATOR_OBJECT_ITEMSTACK_FE_CAPACITY;
  OBJECT_ITEMSTACK_HASINVENTORY = OPERATOR_OBJECT_ITEMSTACK_HASINVENTORY;
  OBJECT_ITEMSTACK_INVENTORYSIZE = OPERATOR_OBJECT_ITEMSTACK_INVENTORYSIZE;
  OBJECT_ITEMSTACK_INVENTORY = OPERATOR_OBJECT_ITEMSTACK_INVENTORY;
  ITEMSTACK_ITEMBYNAME = OPERATOR_ITEMSTACK_ITEMBYNAME;
  ITEMSTACK_ITEMLISTCOUNT = OPERATOR_ITEMSTACK_ITEMLISTCOUNT;
  OBJECT_ITEMSTACK_NBT = OPERATOR_OBJECT_ITEMSTACK_NBT;
  OBJECT_ITEMSTACK_PLANT = OPERATOR_OBJECT_ITEMSTACK_PLANT;
  OBJECT_ITEMSTACK_PLANTTYPE = OPERATOR_OBJECT_ITEMSTACK_PLANTTYPE;
  OBJECT_ITEMSTACK_HASNBT = OPERATOR_OBJECT_ITEMSTACK_HASNBT;
  OBJECT_ITEMSTACK_DATA_KEYS = OPERATOR_OBJECT_ITEMSTACK_DATA_KEYS;
  ITEMSTACK_DATAVALUE = OPERATOR_ITEMSTACK_DATAVALUE;
  ITEMSTACK_WITHDATA = OPERATOR_ITEMSTACK_WITHDATA;
  ITEMSTACK_WITH_NBT = OPERATOR_ITEMSTACK_WITH_NBT;
  ITEMSTACK_TOOLTIP = OPERATOR_ITEMSTACK_TOOLTIP;
  OBJECT_ITEMSTACK_TAG = OPERATOR_OBJECT_ITEMSTACK_TAG;
  OBJECT_ENTITY_ENTITYITEMTOOLTIP = OPERATOR_OBJECT_ENTITY_ENTITYITEMTOOLTIP;
  OBJECT_ENTITY_ISMOB = OPERATOR_OBJECT_ENTITY_ISMOB;
  OBJECT_ENTITY_ISANIMAL = OPERATOR_OBJECT_ENTITY_ISANIMAL;
  OBJECT_ENTITY_ISITEM = OPERATOR_OBJECT_ENTITY_ISITEM;
  OBJECT_ENTITY_ISPLAYER = OPERATOR_OBJECT_ENTITY_ISPLAYER;
  ENTITY_ISMINECART = OPERATOR_ENTITY_ISMINECART;
  ENTITY_ITEM = OPERATOR_ENTITY_ITEM;
  ENTITY_HEALTH = OPERATOR_ENTITY_HEALTH;
  ENTITY_WIDTH = OPERATOR_ENTITY_WIDTH;
  OBJECT_ENTITY_WIDTH = OPERATOR_OBJECT_ENTITY_WIDTH;
  OBJECT_ENTITY_HEIGHT = OPERATOR_OBJECT_ENTITY_HEIGHT;
  OBJECT_ENTITY_ISBURNING = OPERATOR_OBJECT_ENTITY_ISBURNING;
  OBJECT_ENTITY_ISWET = OPERATOR_OBJECT_ENTITY_ISWET;
  OBJECT_ENTITY_ISCROUCHING = OPERATOR_OBJECT_ENTITY_ISCROUCHING;
  OBJECT_ENTITY_ISEATING = OPERATOR_OBJECT_ENTITY_ISEATING;
  ENTITY_ARMORINVENTORY = OPERATOR_ENTITY_ARMORINVENTORY;
  OBJECT_ENTITY_INVENTORY = OPERATOR_OBJECT_ENTITY_INVENTORY;
  OBJECT_ENTITY_MODNAME = OPERATOR_OBJECT_ENTITY_MODNAME;
  OBJECT_PLAYER_TARGETBLOCK = OPERATOR_OBJECT_PLAYER_TARGETBLOCK;
  OBJECT_PLAYER_TARGETENTITY = OPERATOR_OBJECT_PLAYER_TARGETENTITY;
  ENTITY_HASGUIOPEN = OPERATOR_ENTITY_HASGUIOPEN;
  ENTITY_HELDITEM = OPERATOR_ENTITY_HELDITEM;
  ENTITY_HELDITEMOFFHAND = OPERATOR_ENTITY_HELDITEMOFFHAND;
  OBJECT_ENTITY_MOUNTED = OPERATOR_OBJECT_ENTITY_MOUNTED;
  OBJECT_ITEMFRAME_CONTENTS = OPERATOR_OBJECT_ITEMFRAME_CONTENTS;
  OBJECT_ITEMFRAME_ROTATION = OPERATOR_OBJECT_ITEMFRAME_ROTATION;
  OBJECT_ENTITY_HURTSOUND = OPERATOR_OBJECT_ENTITY_HURTSOUND;
  OBJECT_ENTITY_DEATHSOUND = OPERATOR_OBJECT_ENTITY_DEATHSOUND;
  OBJECT_ENTITY_AGE = OPERATOR_OBJECT_ENTITY_AGE;
  OBJECT_ENTITY_ISCHILD = OPERATOR_OBJECT_ENTITY_ISCHILD;
  OBJECT_ENTITY_CANBREED = OPERATOR_OBJECT_ENTITY_CANBREED;
  OBJECT_ENTITY_ISINLOVE = OPERATOR_OBJECT_ENTITY_ISINLOVE;
  OBJECT_ENTITY_CANBREEDWITH = OPERATOR_OBJECT_ENTITY_CANBREEDWITH;
  OBJECT_ENTITY_ISSHEARABLE = OPERATOR_OBJECT_ENTITY_ISSHEARABLE;
  OBJECT_ENTITY_NBT = OPERATOR_OBJECT_ENTITY_NBT;
  OBJECT_ENTITY_TYPE = OPERATOR_OBJECT_ENTITY_TYPE;
  OBJECT_ENTITY_ITEMS = OPERATOR_OBJECT_ENTITY_ITEMS;
  OBJECT_ENTITY_FLUIDS = OPERATOR_OBJECT_ENTITY_FLUIDS;
  OBJECT_ENTITY_ENERGY_STORED = OPERATOR_OBJECT_ENTITY_ENERGY_STORED;
  OBJECT_ENTITY_ENERGY_CAPACITY = OPERATOR_OBJECT_ENTITY_ENERGY_CAPACITY;
  OBJECT_FLUIDSTACK_AMOUNT = OPERATOR_OBJECT_FLUIDSTACK_AMOUNT;
  OBJECT_FLUIDSTACK_BLOCK = OPERATOR_OBJECT_FLUIDSTACK_BLOCK;
  OBJECT_FLUIDSTACK_LIGHT_LEVEL = OPERATOR_OBJECT_FLUIDSTACK_LIGHT_LEVEL;
  OBJECT_FLUIDSTACK_DENSITY = OPERATOR_OBJECT_FLUIDSTACK_DENSITY;
  OBJECT_FLUIDSTACK_TEMPERATURE = OPERATOR_OBJECT_FLUIDSTACK_TEMPERATURE;
  OBJECT_FLUIDSTACK_VISCOSITY = OPERATOR_OBJECT_FLUIDSTACK_VISCOSITY;
  OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR =
    OPERATOR_OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR;
  OBJECT_FLUIDSTACK_RARITY = OPERATOR_OBJECT_FLUIDSTACK_RARITY;
  OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY =
    OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY;
  OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE =
    OPERATOR_OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE;
  OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL =
    OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL;
  OBJECT_FLUIDSTACK_BUCKET = OPERATOR_OBJECT_FLUIDSTACK_BUCKET;
  OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL =
    OPERATOR_OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL;
  OBJECT_FLUIDSTACK_MODNAME = OPERATOR_OBJECT_FLUIDSTACK_MODNAME;
  OBJECT_FLUIDSTACK_DATA = OPERATOR_OBJECT_FLUIDSTACK_DATA;
  OBJECT_FLUIDSTACK_WITH_AMOUNT = OPERATOR_OBJECT_FLUIDSTACK_WITH_AMOUNT;
  OBJECT_FLUIDSTACK_DATAKEYS = OPERATOR_OBJECT_FLUIDSTACK_DATAKEYS;
  OBJECT_FLUIDSTACK_DATA_VALUE = OPERATOR_OBJECT_FLUIDSTACK_DATA_VALUE;
  OBJECT_FLUIDSTACK_WITH_DATA = OPERATOR_OBJECT_FLUIDSTACK_WITH_DATA;
  OBJECT_FLUIDSTACK_WITH_NBT = OPERATOR_OBJECT_FLUIDSTACK_WITH_NBT;
  OBJECT_FLUIDSTACK_BY_NAME = OPERATOR_OBJECT_FLUIDSTACK_BY_NAME;
  OBJECT_FLUIDSTACK_TAG = OPERATOR_OBJECT_FLUIDSTACK_TAG;
  OBJECT_FLUIDSTACK_TAG_STACKS = OPERATOR_OBJECT_FLUIDSTACK_TAG_STACKS;
  OPERATOR_APPLY = OPERATOR_OPERATOR_APPLY;
  OPERATOR_APPLY_2 = OPERATOR_OPERATOR_APPLY_2;
  OPERATOR_APPLY_3 = OPERATOR_OPERATOR_APPLY_3;
  OPERATOR_APPLY_N = OPERATOR_OPERATOR_APPLY_N;
  OPERATOR_APPLY_0 = OPERATOR_OPERATOR_APPLY_0;
  OPERATOR_MAP = OPERATOR_OPERATOR_MAP;
  OPERATOR_FILTER = OPERATOR_OPERATOR_FILTER;
  OPERATOR_CONJUNCTION = OPERATOR_OPERATOR_CONJUNCTION;
  OPERATOR_DISJUNCTION = OPERATOR_OPERATOR_DISJUNCTION;
  OPERATOR_NEGATION = OPERATOR_OPERATOR_NEGATION;
  OPERATOR_PIPE = OPERATOR_OPERATOR_PIPE;
  OPERATOR_PIPE2 = OPERATOR_OPERATOR_PIPE2;
  OPERATOR_FLIP = OPERATOR_OPERATOR_FLIP;
  OPERATOR_REDUCE = OPERATOR_OPERATOR_REDUCE;
  OPERATOR_REDUCE1 = OPERATOR_OPERATOR_REDUCE1;
  OPERATOR_BY_NAME = OPERATOR_OPERATOR_BY_NAME;
  NBT_COMPOUND_SIZE = OPERATOR_NBT_COMPOUND_SIZE;
  NBT_COMPOUND_KEYS = OPERATOR_NBT_COMPOUND_KEYS;
  NBT_COMPOUND_HASKEY = OPERATOR_NBT_COMPOUND_HASKEY;
  NBT_COMPOUND_VALUE_TYPE = OPERATOR_NBT_COMPOUND_VALUE_TYPE;
  NBT_COMPOUND_VALUE_TAG = OPERATOR_NBT_COMPOUND_VALUE_TAG;
  NBT_COMPOUND_VALUE_BOOLEAN = OPERATOR_NBT_COMPOUND_VALUE_BOOLEAN;
  NBT_COMPOUND_VALUE_INTEGER = OPERATOR_NBT_COMPOUND_VALUE_INTEGER;
  NBT_COMPOUND_VALUE_LONG = OPERATOR_NBT_COMPOUND_VALUE_LONG;
  NBT_COMPOUND_VALUE_DOUBLE = OPERATOR_NBT_COMPOUND_VALUE_DOUBLE;
  NBT_COMPOUND_VALUE_STRING = OPERATOR_NBT_COMPOUND_VALUE_STRING;
  NBT_COMPOUND_VALUE_COMPOUND = OPERATOR_NBT_COMPOUND_VALUE_COMPOUND;
  NBT_COMPOUND_VALUE_LIST_TAG = OPERATOR_NBT_COMPOUND_VALUE_LIST_TAG;
  NBT_COMPOUND_VALUE_LIST_BYTE = OPERATOR_NBT_COMPOUND_VALUE_LIST_BYTE;
  NBT_COMPOUND_VALUE_LIST_INT = OPERATOR_NBT_COMPOUND_VALUE_LIST_INT;
  NBT_COMPOUND_VALUE_LIST_LONG = OPERATOR_NBT_COMPOUND_VALUE_LIST_LONG;
  NBT_COMPOUND_WITHOUT = OPERATOR_NBT_COMPOUND_WITHOUT;
  NBT_COMPOUND_WITH_BOOLEAN = OPERATOR_NBT_COMPOUND_WITH_BOOLEAN;
  NBT_COMPOUND_WITH_SHORT = OPERATOR_NBT_COMPOUND_WITH_SHORT;
  NBT_COMPOUND_WITH_INTEGER = OPERATOR_NBT_COMPOUND_WITH_INTEGER;
  NBT_COMPOUND_WITH_LONG = OPERATOR_NBT_COMPOUND_WITH_LONG;
  NBT_COMPOUND_WITH_DOUBLE = OPERATOR_NBT_COMPOUND_WITH_DOUBLE;
  NBT_COMPOUND_WITH_FLOAT = OPERATOR_NBT_COMPOUND_WITH_FLOAT;
  NBT_COMPOUND_WITH_STRING = OPERATOR_NBT_COMPOUND_WITH_STRING;
  NBT_COMPOUND_WITH_COMPOUND = OPERATOR_NBT_COMPOUND_WITH_COMPOUND;
  NBT_COMPOUND_WITH_LIST_TAG = OPERATOR_NBT_COMPOUND_WITH_LIST_TAG;
  NBT_COMPOUND_WITH_LIST_BYTE = OPERATOR_NBT_COMPOUND_WITH_LIST_BYTE;
  NBT_COMPOUND_WITH_LIST_INT = OPERATOR_NBT_COMPOUND_WITH_LIST_INT;
  NBT_COMPOUND_WITH_LIST_LONG = OPERATOR_NBT_COMPOUND_WITH_LIST_LONG;
  NBT_COMPOUND_SUBSET = OPERATOR_NBT_COMPOUND_SUBSET;
  NBT_COMPOUND_UNION = OPERATOR_NBT_COMPOUND_UNION;
  NBT_COMPOUND_INTERSECTION = OPERATOR_NBT_COMPOUND_INTERSECTION;
  NBT_COMPOUND_MINUS = OPERATOR_NBT_COMPOUND_MINUS;
  NBT_AS_BOOLEAN = OPERATOR_NBT_AS_BOOLEAN;
  NBT_AS_BYTE = OPERATOR_NBT_AS_BYTE;
  NBT_AS_SHORT = OPERATOR_NBT_AS_SHORT;
  NBT_AS_INT = OPERATOR_NBT_AS_INT;
  NBT_AS_LONG = OPERATOR_NBT_AS_LONG;
  NBT_AS_DOUBLE = OPERATOR_NBT_AS_DOUBLE;
  NBT_AS_FLOAT = OPERATOR_NBT_AS_FLOAT;
  NBT_AS_STRING = OPERATOR_NBT_AS_STRING;
  NBT_AS_TAG_LIST = OPERATOR_NBT_AS_TAG_LIST;
  NBT_AS_BYTE_LIST = OPERATOR_NBT_AS_BYTE_LIST;
  NBT_AS_INT_LIST = OPERATOR_NBT_AS_INT_LIST;
  NBT_AS_LONG_LIST = OPERATOR_NBT_AS_LONG_LIST;
  NBT_FROM_BOOLEAN = OPERATOR_NBT_FROM_BOOLEAN;
  NBT_FROM_SHORT = OPERATOR_NBT_FROM_SHORT;
  NBT_FROM_BYTE = OPERATOR_NBT_FROM_BYTE;
  NBT_FROM_INT = OPERATOR_NBT_FROM_INT;
  NBT_FROM_LONG = OPERATOR_NBT_FROM_LONG;
  NBT_FROM_DOUBLE = OPERATOR_NBT_FROM_DOUBLE;
  NBT_FROM_FLOAT = OPERATOR_NBT_FROM_FLOAT;
  NBT_FROM_STRING = OPERATOR_NBT_FROM_STRING;
  NBT_FROM_TAG_LIST = OPERATOR_NBT_FROM_TAG_LIST;
  NBT_FROM_BYTE_LIST = OPERATOR_NBT_FROM_BYTE_LIST;
  NBT_FROM_INT_LIST = OPERATOR_NBT_FROM_INT_LIST;
  NBT_FROM_LONG_LIST = OPERATOR_NBT_FROM_LONG_LIST;
  NBT_PATH_MATCH_FIRST = OPERATOR_NBT_PATH_MATCH_FIRST;
  NBT_PATH_MATCH_ALL = OPERATOR_NBT_PATH_MATCH_ALL;
  NBT_PATH_TEST = OPERATOR_NBT_PATH_TEST;
  INGREDIENTS_ITEMS = OPERATOR_INGREDIENTS_ITEMS;
  INGREDIENTS_FLUIDS = OPERATOR_INGREDIENTS_FLUIDS;
  INGREDIENTS_ENERGIES = OPERATOR_INGREDIENTS_ENERGIES;
  INGREDIENTS_WITH_ITEM = OPERATOR_INGREDIENTS_WITH_ITEM;
  INGREDIENTS_WITH_FLUID = OPERATOR_INGREDIENTS_WITH_FLUID;
  INGREDIENTS_WITH_ENERGY = OPERATOR_INGREDIENTS_WITH_ENERGY;
  INGREDIENTS_WITH_ITEMS = OPERATOR_INGREDIENTS_WITH_ITEMS;
  INGREDIENTS_WITH_FLUIDS = OPERATOR_INGREDIENTS_WITH_FLUIDS;
  INGREDIENTS_WITH_ENERGIES = OPERATOR_INGREDIENTS_WITH_ENERGIES;
  RECIPE_INPUT = OPERATOR_RECIPE_INPUT;
  RECIPE_OUTPUT = OPERATOR_RECIPE_OUTPUT;
  RECIPE_WITH_INPUT = OPERATOR_RECIPE_WITH_INPUT;
  RECIPE_WITH_OUTPUT = OPERATOR_RECIPE_WITH_OUTPUT;
  RECIPE_WITH_INPUT_OUTPUT = OPERATOR_RECIPE_WITH_INPUT_OUTPUT;
  PARSE_BOOLEAN = OPERATOR_PARSE_BOOLEAN;
  PARSE_DOUBLE = OPERATOR_PARSE_DOUBLE;
  PARSE_INTEGER = OPERATOR_PARSE_INTEGER;
  PARSE_LONG = OPERATOR_PARSE_LONG;
  PARSE_NBT = OPERATOR_PARSE_NBT;
  GENERAL_CHOICE = OPERATOR_GENERAL_CHOICE;
  GENERAL_IDENTITY = OPERATOR_GENERAL_IDENTITY;
  GENERAL_CONSTANT = OPERATOR_GENERAL_CONSTANT;
  INTEGER_TO_DOUBLE = OPERATOR_INTEGER_TO_DOUBLE;
  INTEGER_TO_LONG = OPERATOR_INTEGER_TO_LONG;
  DOUBLE_TO_INTEGER = OPERATOR_DOUBLE_TO_INTEGER;
  DOUBLE_TO_LONG = OPERATOR_DOUBLE_TO_LONG;
  LONG_TO_INTEGER = OPERATOR_LONG_TO_INTEGER;
  LONG_TO_DOUBLE = OPERATOR_LONG_TO_DOUBLE;
};

const operatorRegistry = new operatorRegistryClass();
RegistryHub.operatorRegistry = operatorRegistry;
export { operatorRegistry };
