import { TypeMap } from "HelperClasses/TypeMap";
import { OPERATOR_ARITHMETIC_ADDITION } from "./operators/ARITHMETIC_ADDITION";
import { OPERATOR_ARITHMETIC_DECREMENT } from "./operators/ARITHMETIC_DECREMENT";
import { OPERATOR_ARITHMETIC_DIVISION } from "./operators/ARITHMETIC_DIVISION";
import { OPERATOR_ARITHMETIC_INCREMENT } from "./operators/ARITHMETIC_INCREMENT";
import { OPERATOR_ARITHMETIC_MAXIMUM } from "./operators/ARITHMETIC_MAXIMUM";
import { OPERATOR_ARITHMETIC_MINIMUM } from "./operators/ARITHMETIC_MINIMUM";
import { OPERATOR_ARITHMETIC_MODULUS } from "./operators/ARITHMETIC_MODULUS";
import { OPERATOR_ARITHMETIC_MULTIPLICATION } from "./operators/ARITHMETIC_MULTIPLICATION";
import { OPERATOR_ARITHMETIC_SUBTRACTION } from "./operators/ARITHMETIC_SUBTRACTION";
import { OPERATOR_BINARY_AND } from "./operators/BINARY_AND";
import { OPERATOR_BINARY_COMPLEMENT } from "./operators/BINARY_COMPLEMENT";
import { OPERATOR_BINARY_LSHIFT } from "./operators/BINARY_LSHIFT";
import { OPERATOR_BINARY_OR } from "./operators/BINARY_OR";
import { OPERATOR_BINARY_RSHIFT } from "./operators/BINARY_RSHIFT";
import { OPERATOR_BINARY_XOR } from "./operators/BINARY_XOR";
import { OPERATOR_DOUBLE_POW } from "./operators/DOUBLE_POW";
import { OPERATOR_DOUBLE_SQRT } from "./operators/DOUBLE_SQRT";
import { OPERATOR_DOUBLE_TO_INTEGER } from "./operators/DOUBLE_TO_INTEGER";
import { OPERATOR_DOUBLE_TO_LONG } from "./operators/DOUBLE_TO_LONG";
import { OPERATOR_ENTITY_ARMORINVENTORY } from "./operators/ENTITY_ARMORINVENTORY";
import { OPERATOR_ENTITY_HASGUIOPEN } from "./operators/ENTITY_HASGUIOPEN";
import { OPERATOR_ENTITY_HEALTH } from "./operators/ENTITY_HEALTH";
import { OPERATOR_ENTITY_HELDITEM } from "./operators/ENTITY_HELDITEM";
import { OPERATOR_ENTITY_HELDITEMOFFHAND } from "./operators/ENTITY_HELDITEMOFFHAND";
import { OPERATOR_ENTITY_ISMINECART } from "./operators/ENTITY_ISMINECART";
import { OPERATOR_ENTITY_ITEM } from "./operators/ENTITY_ITEM";
import { OPERATOR_ENTITY_WIDTH } from "./operators/ENTITY_WIDTH";
import { OPERATOR_GENERAL_CHOICE } from "./operators/GENERAL_CHOICE";
import { OPERATOR_GENERAL_CONSTANT } from "./operators/GENERAL_CONSTANT";
import { OPERATOR_GENERAL_IDENTITY } from "./operators/GENERAL_IDENTITY";
import { OPERATOR_INGREDIENTS_ENERGIES } from "./operators/INGREDIENTS_ENERGIES";
import { OPERATOR_INGREDIENTS_FLUIDS } from "./operators/INGREDIENTS_FLUIDS";
import { OPERATOR_INGREDIENTS_ITEMS } from "./operators/INGREDIENTS_ITEMS";
import { OPERATOR_INGREDIENTS_WITH_ENERGIES } from "./operators/INGREDIENTS_WITH_ENERGIES";
import { OPERATOR_INGREDIENTS_WITH_ENERGY } from "./operators/INGREDIENTS_WITH_ENERGY";
import { OPERATOR_INGREDIENTS_WITH_FLUID } from "./operators/INGREDIENTS_WITH_FLUID";
import { OPERATOR_INGREDIENTS_WITH_FLUIDS } from "./operators/INGREDIENTS_WITH_FLUIDS";
import { OPERATOR_INGREDIENTS_WITH_ITEM } from "./operators/INGREDIENTS_WITH_ITEM";
import { OPERATOR_INGREDIENTS_WITH_ITEMS } from "./operators/INGREDIENTS_WITH_ITEMS";
import { OPERATOR_INTEGER_TO_DOUBLE } from "./operators/INTEGER_TO_DOUBLE";
import { OPERATOR_INTEGER_TO_LONG } from "./operators/INTEGER_TO_LONG";
import { OPERATOR_ITEMSTACK_CANBURN } from "./operators/ITEMSTACK_CANBURN";
import { OPERATOR_ITEMSTACK_DATAVALUE } from "./operators/ITEMSTACK_DATAVALUE";
import { OPERATOR_ITEMSTACK_ISFECONTAINER } from "./operators/ITEMSTACK_ISFECONTAINER";
import { OPERATOR_ITEMSTACK_ITEMBYNAME } from "./operators/ITEMSTACK_ITEMBYNAME";
import { OPERATOR_ITEMSTACK_ITEMLISTCOUNT } from "./operators/ITEMSTACK_ITEMLISTCOUNT";
import { OPERATOR_ITEMSTACK_TAG } from "./operators/ITEMSTACK_TAG";
import { OPERATOR_ITEMSTACK_TOOLTIP } from "./operators/ITEMSTACK_TOOLTIP";
import { OPERATOR_ITEMSTACK_WITHDATA } from "./operators/ITEMSTACK_WITHDATA";
import { OPERATOR_LIST_APPEND } from "./operators/LIST_APPEND";
import { OPERATOR_LIST_CONCAT } from "./operators/LIST_CONCAT";
import { OPERATOR_LIST_CONTAINS } from "./operators/LIST_CONTAINS";
import { OPERATOR_LIST_CONTAINS_PREDICATE } from "./operators/LIST_CONTAINS_PREDICATE";
import { OPERATOR_LIST_COUNT } from "./operators/LIST_COUNT";
import { OPERATOR_LIST_COUNT_PREDICATE } from "./operators/LIST_COUNT_PREDICATE";
import { OPERATOR_LIST_ELEMENT } from "./operators/LIST_ELEMENT";
import { OPERATOR_LIST_ELEMENT_DEFAULT } from "./operators/LIST_ELEMENT_DEFAULT";
import { OPERATOR_LIST_EMPTY } from "./operators/LIST_EMPTY";
import { OPERATOR_LIST_EQUALS_MULTISET } from "./operators/LIST_EQUALS_MULTISET";
import { OPERATOR_LIST_EQUALS_SET } from "./operators/LIST_EQUALS_SET";
import { OPERATOR_LIST_HEAD } from "./operators/LIST_HEAD";
import { OPERATOR_LIST_INTERSECTION } from "./operators/LIST_INTERSECTION";
import { OPERATOR_LIST_LENGTH } from "./operators/LIST_LENGTH";
import { OPERATOR_LIST_NOT_EMPTY } from "./operators/LIST_NOT_EMPTY";
import { OPERATOR_LIST_SLICE } from "./operators/LIST_SLICE";
import { OPERATOR_LIST_TAIL } from "./operators/LIST_TAIL";
import { OPERATOR_LIST_UNIQ } from "./operators/LIST_UNIQ";
import { OPERATOR_LIST_UNIQ_PREDICATE } from "./operators/LIST_UNIQ_PREDICATE";
import { OPERATOR_LOGICAL_AND } from "./operators/LOGICAL_AND";
import { OPERATOR_LOGICAL_NAND } from "./operators/LOGICAL_NAND";
import { OPERATOR_LOGICAL_NOR } from "./operators/LOGICAL_NOR";
import { OPERATOR_LOGICAL_NOT } from "./operators/LOGICAL_NOT";
import { OPERATOR_LOGICAL_OR } from "./operators/LOGICAL_OR";
import { OPERATOR_LONG_TO_DOUBLE } from "./operators/LONG_TO_DOUBLE";
import { OPERATOR_LONG_TO_INTEGER } from "./operators/LONG_TO_INTEGER";
import { OPERATOR_NAMED_NAME } from "./operators/NAMED_NAME";
import { OPERATOR_NBT_AS_BOOLEAN } from "./operators/NBT_AS_BOOLEAN";
import { OPERATOR_NBT_AS_BYTE } from "./operators/NBT_AS_BYTE";
import { OPERATOR_NBT_AS_BYTE_LIST } from "./operators/NBT_AS_BYTE_LIST";
import { OPERATOR_NBT_AS_DOUBLE } from "./operators/NBT_AS_DOUBLE";
import { OPERATOR_NBT_AS_FLOAT } from "./operators/NBT_AS_FLOAT";
import { OPERATOR_NBT_AS_INT } from "./operators/NBT_AS_INT";
import { OPERATOR_NBT_AS_INT_LIST } from "./operators/NBT_AS_INT_LIST";
import { OPERATOR_NBT_AS_LONG } from "./operators/NBT_AS_LONG";
import { OPERATOR_NBT_AS_LONG_LIST } from "./operators/NBT_AS_LONG_LIST";
import { OPERATOR_NBT_AS_SHORT } from "./operators/NBT_AS_SHORT";
import { OPERATOR_NBT_AS_STRING } from "./operators/NBT_AS_STRING";
import { OPERATOR_NBT_AS_TAG_LIST } from "./operators/NBT_AS_TAG_LIST";
import { OPERATOR_NBT_COMPOUND_HASKEY } from "./operators/NBT_COMPOUND_HASKEY";
import { OPERATOR_NBT_COMPOUND_INTERSECTION } from "./operators/NBT_COMPOUND_INTERSECTION";
import { OPERATOR_NBT_COMPOUND_KEYS } from "./operators/NBT_COMPOUND_KEYS";
import { OPERATOR_NBT_COMPOUND_MINUS } from "./operators/NBT_COMPOUND_MINUS";
import { OPERATOR_NBT_COMPOUND_SIZE } from "./operators/NBT_COMPOUND_SIZE";
import { OPERATOR_NBT_COMPOUND_SUBSET } from "./operators/NBT_COMPOUND_SUBSET";
import { OPERATOR_NBT_COMPOUND_UNION } from "./operators/NBT_COMPOUND_UNION";
import { OPERATOR_NBT_COMPOUND_VALUE_BOOLEAN } from "./operators/NBT_COMPOUND_VALUE_BOOLEAN";
import { OPERATOR_NBT_COMPOUND_VALUE_COMPOUND } from "./operators/NBT_COMPOUND_VALUE_COMPOUND";
import { OPERATOR_NBT_COMPOUND_VALUE_DOUBLE } from "./operators/NBT_COMPOUND_VALUE_DOUBLE";
import { OPERATOR_NBT_COMPOUND_VALUE_INTEGER } from "./operators/NBT_COMPOUND_VALUE_INTEGER";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_BYTE } from "./operators/NBT_COMPOUND_VALUE_LIST_BYTE";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_INT } from "./operators/NBT_COMPOUND_VALUE_LIST_INT";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_LONG } from "./operators/NBT_COMPOUND_VALUE_LIST_LONG";
import { OPERATOR_NBT_COMPOUND_VALUE_LIST_TAG } from "./operators/NBT_COMPOUND_VALUE_LIST_TAG";
import { OPERATOR_NBT_COMPOUND_VALUE_LONG } from "./operators/NBT_COMPOUND_VALUE_LONG";
import { OPERATOR_NBT_COMPOUND_VALUE_STRING } from "./operators/NBT_COMPOUND_VALUE_STRING";
import { OPERATOR_NBT_COMPOUND_VALUE_TAG } from "./operators/NBT_COMPOUND_VALUE_TAG";
import { OPERATOR_NBT_COMPOUND_VALUE_TYPE } from "./operators/NBT_COMPOUND_VALUE_TYPE";
import { OPERATOR_NBT_COMPOUND_WITH_BOOLEAN } from "./operators/NBT_COMPOUND_WITH_BOOLEAN";
import { OPERATOR_NBT_COMPOUND_WITH_COMPOUND } from "./operators/NBT_COMPOUND_WITH_COMPOUND";
import { OPERATOR_NBT_COMPOUND_WITH_DOUBLE } from "./operators/NBT_COMPOUND_WITH_DOUBLE";
import { OPERATOR_NBT_COMPOUND_WITH_FLOAT } from "./operators/NBT_COMPOUND_WITH_FLOAT";
import { OPERATOR_NBT_COMPOUND_WITH_INTEGER } from "./operators/NBT_COMPOUND_WITH_INTEGER";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_BYTE } from "./operators/NBT_COMPOUND_WITH_LIST_BYTE";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_INT } from "./operators/NBT_COMPOUND_WITH_LIST_INT";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_LONG } from "./operators/NBT_COMPOUND_WITH_LIST_LONG";
import { OPERATOR_NBT_COMPOUND_WITH_LIST_TAG } from "./operators/NBT_COMPOUND_WITH_LIST_TAG";
import { OPERATOR_NBT_COMPOUND_WITH_LONG } from "./operators/NBT_COMPOUND_WITH_LONG";
import { OPERATOR_NBT_COMPOUND_WITH_SHORT } from "./operators/NBT_COMPOUND_WITH_SHORT";
import { OPERATOR_NBT_COMPOUND_WITH_STRING } from "./operators/NBT_COMPOUND_WITH_STRING";
import { OPERATOR_NBT_COMPOUND_WITHOUT } from "./operators/NBT_COMPOUND_WITHOUT";
import { OPERATOR_NBT_FROM_BOOLEAN } from "./operators/NBT_FROM_BOOLEAN";
import { OPERATOR_NBT_FROM_BYTE } from "./operators/NBT_FROM_BYTE";
import { OPERATOR_NBT_FROM_BYTE_LIST } from "./operators/NBT_FROM_BYTE_LIST";
import { OPERATOR_NBT_FROM_DOUBLE } from "./operators/NBT_FROM_DOUBLE";
import { OPERATOR_NBT_FROM_FLOAT } from "./operators/NBT_FROM_FLOAT";
import { OPERATOR_NBT_FROM_INT } from "./operators/NBT_FROM_INT";
import { OPERATOR_NBT_FROM_INT_LIST } from "./operators/NBT_FROM_INT_LIST";
import { OPERATOR_NBT_FROM_LONG } from "./operators/NBT_FROM_LONG";
import { OPERATOR_NBT_FROM_LONG_LIST } from "./operators/NBT_FROM_LONG_LIST";
import { OPERATOR_NBT_FROM_SHORT } from "./operators/NBT_FROM_SHORT";
import { OPERATOR_NBT_FROM_STRING } from "./operators/NBT_FROM_STRING";
import { OPERATOR_NBT_FROM_TAG_LIST } from "./operators/NBT_FROM_TAG_LIST";
import { OPERATOR_NBT_PATH_MATCH_ALL } from "./operators/NBT_PATH_MATCH_ALL";
import { OPERATOR_NBT_PATH_MATCH_FIRST } from "./operators/NBT_PATH_MATCH_FIRST";
import { OPERATOR_NBT_PATH_TEST } from "./operators/NBT_PATH_TEST";
import { OPERATOR_NULLABLE_ISNOTNULL } from "./operators/NULLABLE_ISNOTNULL";
import { OPERATOR_NULLABLE_ISNULL } from "./operators/NULLABLE_ISNULL";
import { OPERATOR_NUMBER_CEIL } from "./operators/NUMBER_CEIL";
import { OPERATOR_NUMBER_COMPACT } from "./operators/NUMBER_COMPACT";
import { OPERATOR_NUMBER_FLOOR } from "./operators/NUMBER_FLOOR";
import { OPERATOR_NUMBER_ROUND } from "./operators/NUMBER_ROUND";
import { OPERATOR_OBJECT_BLOCK_BREAKSOUND } from "./operators/OBJECT_BLOCK_BREAKSOUND";
import { OPERATOR_OBJECT_BLOCK_BY_NAME } from "./operators/OBJECT_BLOCK_BY_NAME";
import { OPERATOR_OBJECT_BLOCK_ISSHEARABLE } from "./operators/OBJECT_BLOCK_ISSHEARABLE";
import { OPERATOR_OBJECT_BLOCK_ITEMSTACK } from "./operators/OBJECT_BLOCK_ITEMSTACK";
import { OPERATOR_OBJECT_BLOCK_MODNAME } from "./operators/OBJECT_BLOCK_MODNAME";
import { OPERATOR_OBJECT_BLOCK_OPAQUE } from "./operators/OBJECT_BLOCK_OPAQUE";
import { OPERATOR_OBJECT_BLOCK_PLACESOUND } from "./operators/OBJECT_BLOCK_PLACESOUND";
import { OPERATOR_OBJECT_BLOCK_PLANTAGE } from "./operators/OBJECT_BLOCK_PLANTAGE";
import { OPERATOR_OBJECT_BLOCK_POSSIBLE_PROPERTIES } from "./operators/OBJECT_BLOCK_POSSIBLE_PROPERTIES";
import { OPERATOR_OBJECT_BLOCK_PROPERTIES } from "./operators/OBJECT_BLOCK_PROPERTIES";
import { OPERATOR_OBJECT_BLOCK_STEPSOUND } from "./operators/OBJECT_BLOCK_STEPSOUND";
import { OPERATOR_OBJECT_BLOCK_TAG } from "./operators/OBJECT_BLOCK_TAG";
import { OPERATOR_OBJECT_BLOCK_TAG_STACKS } from "./operators/OBJECT_BLOCK_TAG_STACKS";
import { OPERATOR_OBJECT_BLOCK_WITH_PROPERTIES } from "./operators/OBJECT_BLOCK_WITH_PROPERTIES";
import { OPERATOR_OBJECT_ENTITY_AGE } from "./operators/OBJECT_ENTITY_AGE";
import { OPERATOR_OBJECT_ENTITY_CANBREED } from "./operators/OBJECT_ENTITY_CANBREED";
import { OPERATOR_OBJECT_ENTITY_CANBREEDWITH } from "./operators/OBJECT_ENTITY_CANBREEDWITH";
import { OPERATOR_OBJECT_ENTITY_DEATHSOUND } from "./operators/OBJECT_ENTITY_DEATHSOUND";
import { OPERATOR_OBJECT_ENTITY_ENERGY_CAPACITY } from "./operators/OBJECT_ENTITY_ENERGY_CAPACITY";
import { OPERATOR_OBJECT_ENTITY_ENERGY_STORED } from "./operators/OBJECT_ENTITY_ENERGY_STORED";
import { OPERATOR_OBJECT_ENTITY_ENTITYITEMTOOLTIP } from "./operators/OBJECT_ENTITY_ENTITYITEMTOOLTIP";
import { OPERATOR_OBJECT_ENTITY_FLUIDS } from "./operators/OBJECT_ENTITY_FLUIDS";
import { OPERATOR_OBJECT_ENTITY_HEIGHT } from "./operators/OBJECT_ENTITY_HEIGHT";
import { OPERATOR_OBJECT_ENTITY_HURTSOUND } from "./operators/OBJECT_ENTITY_HURTSOUND";
import { OPERATOR_OBJECT_ENTITY_INVENTORY } from "./operators/OBJECT_ENTITY_INVENTORY";
import { OPERATOR_OBJECT_ENTITY_ISANIMAL } from "./operators/OBJECT_ENTITY_ISANIMAL";
import { OPERATOR_OBJECT_ENTITY_ISBURNING } from "./operators/OBJECT_ENTITY_ISBURNING";
import { OPERATOR_OBJECT_ENTITY_ISCHILD } from "./operators/OBJECT_ENTITY_ISCHILD";
import { OPERATOR_OBJECT_ENTITY_ISCROUCHING } from "./operators/OBJECT_ENTITY_ISCROUCHING";
import { OPERATOR_OBJECT_ENTITY_ISEATING } from "./operators/OBJECT_ENTITY_ISEATING";
import { OPERATOR_OBJECT_ENTITY_ISINLOVE } from "./operators/OBJECT_ENTITY_ISINLOVE";
import { OPERATOR_OBJECT_ENTITY_ISITEM } from "./operators/OBJECT_ENTITY_ISITEM";
import { OPERATOR_OBJECT_ENTITY_ISMOB } from "./operators/OBJECT_ENTITY_ISMOB";
import { OPERATOR_OBJECT_ENTITY_ISPLAYER } from "./operators/OBJECT_ENTITY_ISPLAYER";
import { OPERATOR_OBJECT_ENTITY_ISSHEARABLE } from "./operators/OBJECT_ENTITY_ISSHEARABLE";
import { OPERATOR_OBJECT_ENTITY_ISWET } from "./operators/OBJECT_ENTITY_ISWET";
import { OPERATOR_OBJECT_ENTITY_ITEMS } from "./operators/OBJECT_ENTITY_ITEMS";
import { OPERATOR_OBJECT_ENTITY_MODNAME } from "./operators/OBJECT_ENTITY_MODNAME";
import { OPERATOR_OBJECT_ENTITY_MOUNTED } from "./operators/OBJECT_ENTITY_MOUNTED";
import { OPERATOR_OBJECT_ENTITY_NBT } from "./operators/OBJECT_ENTITY_NBT";
import { OPERATOR_OBJECT_ENTITY_TYPE } from "./operators/OBJECT_ENTITY_TYPE";
import { OPERATOR_OBJECT_ENTITY_WIDTH } from "./operators/OBJECT_ENTITY_WIDTH";
import { OPERATOR_OBJECT_FLUIDSTACK_AMOUNT } from "./operators/OBJECT_FLUIDSTACK_AMOUNT";
import { OPERATOR_OBJECT_FLUIDSTACK_BLOCK } from "./operators/OBJECT_FLUIDSTACK_BLOCK";
import { OPERATOR_OBJECT_FLUIDSTACK_BUCKET } from "./operators/OBJECT_FLUIDSTACK_BUCKET";
import { OPERATOR_OBJECT_FLUIDSTACK_BY_NAME } from "./operators/OBJECT_FLUIDSTACK_BY_NAME";
import { OPERATOR_OBJECT_FLUIDSTACK_DATA } from "./operators/OBJECT_FLUIDSTACK_DATA";
import { OPERATOR_OBJECT_FLUIDSTACK_DATA_VALUE } from "./operators/OBJECT_FLUIDSTACK_DATA_VALUE";
import { OPERATOR_OBJECT_FLUIDSTACK_DATAKEYS } from "./operators/OBJECT_FLUIDSTACK_DATAKEYS";
import { OPERATOR_OBJECT_FLUIDSTACK_DENSITY } from "./operators/OBJECT_FLUIDSTACK_DENSITY";
import { OPERATOR_OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR } from "./operators/OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR";
import { OPERATOR_OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL } from "./operators/OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL";
import { OPERATOR_OBJECT_FLUIDSTACK_LIGHT_LEVEL } from "./operators/OBJECT_FLUIDSTACK_LIGHT_LEVEL";
import { OPERATOR_OBJECT_FLUIDSTACK_MODNAME } from "./operators/OBJECT_FLUIDSTACK_MODNAME";
import { OPERATOR_OBJECT_FLUIDSTACK_RARITY } from "./operators/OBJECT_FLUIDSTACK_RARITY";
import { OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY } from "./operators/OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY";
import { OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL } from "./operators/OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL";
import { OPERATOR_OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE } from "./operators/OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE";
import { OPERATOR_OBJECT_FLUIDSTACK_TAG } from "./operators/OBJECT_FLUIDSTACK_TAG";
import { OPERATOR_OBJECT_FLUIDSTACK_TAG_STACKS } from "./operators/OBJECT_FLUIDSTACK_TAG_STACKS";
import { OPERATOR_OBJECT_FLUIDSTACK_TEMPERATURE } from "./operators/OBJECT_FLUIDSTACK_TEMPERATURE";
import { OPERATOR_OBJECT_FLUIDSTACK_VISCOSITY } from "./operators/OBJECT_FLUIDSTACK_VISCOSITY";
import { OPERATOR_OBJECT_FLUIDSTACK_WITH_AMOUNT } from "./operators/OBJECT_FLUIDSTACK_WITH_AMOUNT";
import { OPERATOR_OBJECT_FLUIDSTACK_WITH_DATA } from "./operators/OBJECT_FLUIDSTACK_WITH_DATA";
import { OPERATOR_OBJECT_ITEMFRAME_CONTENTS } from "./operators/OBJECT_ITEMFRAME_CONTENTS";
import { OPERATOR_OBJECT_ITEMFRAME_ROTATION } from "./operators/OBJECT_ITEMFRAME_ROTATION";
import { OPERATOR_OBJECT_ITEMSTACK_BLOCK } from "./operators/OBJECT_ITEMSTACK_BLOCK";
import { OPERATOR_OBJECT_ITEMSTACK_CANHARVESTBLOCK } from "./operators/OBJECT_ITEMSTACK_CANHARVESTBLOCK";
import { OPERATOR_OBJECT_ITEMSTACK_DAMAGE } from "./operators/OBJECT_ITEMSTACK_DAMAGE";
import { OPERATOR_OBJECT_ITEMSTACK_DATA_KEYS } from "./operators/OBJECT_ITEMSTACK_DATA_KEYS";
import { OPERATOR_OBJECT_ITEMSTACK_FE_CAPACITY } from "./operators/OBJECT_ITEMSTACK_FE_CAPACITY";
import { OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACK } from "./operators/OBJECT_ITEMSTACK_FLUIDSTACK";
import { OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY } from "./operators/OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY";
import { OPERATOR_OBJECT_ITEMSTACK_FUELBURNTIME } from "./operators/OBJECT_ITEMSTACK_FUELBURNTIME";
import { OPERATOR_OBJECT_ITEMSTACK_HASINVENTORY } from "./operators/OBJECT_ITEMSTACK_HASINVENTORY";
import { OPERATOR_OBJECT_ITEMSTACK_HASNBT } from "./operators/OBJECT_ITEMSTACK_HASNBT";
import { OPERATOR_OBJECT_ITEMSTACK_INVENTORY } from "./operators/OBJECT_ITEMSTACK_INVENTORY";
import { OPERATOR_OBJECT_ITEMSTACK_INVENTORYSIZE } from "./operators/OBJECT_ITEMSTACK_INVENTORYSIZE";
import { OPERATOR_OBJECT_ITEMSTACK_ISDAMAGEABLE } from "./operators/OBJECT_ITEMSTACK_ISDAMAGEABLE";
import { OPERATOR_OBJECT_ITEMSTACK_ISDATAEQUAL } from "./operators/OBJECT_ITEMSTACK_ISDATAEQUAL";
import { OPERATOR_OBJECT_ITEMSTACK_ISENCHANTABLE } from "./operators/OBJECT_ITEMSTACK_ISENCHANTABLE";
import { OPERATOR_OBJECT_ITEMSTACK_ISENCHANTED } from "./operators/OBJECT_ITEMSTACK_ISENCHANTED";
import { OPERATOR_OBJECT_ITEMSTACK_ISFLUIDSTACK } from "./operators/OBJECT_ITEMSTACK_ISFLUIDSTACK";
import { OPERATOR_OBJECT_ITEMSTACK_ISITEMEQUALNODATA } from "./operators/OBJECT_ITEMSTACK_ISITEMEQUALNODATA";
import { OPERATOR_OBJECT_ITEMSTACK_ISRAWITEMEQUAL } from "./operators/OBJECT_ITEMSTACK_ISRAWITEMEQUAL";
import { OPERATOR_OBJECT_ITEMSTACK_ISSTACKABLE } from "./operators/OBJECT_ITEMSTACK_ISSTACKABLE";
import { OPERATOR_OBJECT_ITEMSTACK_MAXDAMAGE } from "./operators/OBJECT_ITEMSTACK_MAXDAMAGE";
import { OPERATOR_OBJECT_ITEMSTACK_MAXSIZE } from "./operators/OBJECT_ITEMSTACK_MAXSIZE";
import { OPERATOR_OBJECT_ITEMSTACK_MODNAME } from "./operators/OBJECT_ITEMSTACK_MODNAME";
import { OPERATOR_OBJECT_ITEMSTACK_NBT } from "./operators/OBJECT_ITEMSTACK_NBT";
import { OPERATOR_OBJECT_ITEMSTACK_RARITY } from "./operators/OBJECT_ITEMSTACK_RARITY";
import { OPERATOR_OBJECT_ITEMSTACK_REPAIRCOST } from "./operators/OBJECT_ITEMSTACK_REPAIRCOST";
import { OPERATOR_OBJECT_ITEMSTACK_SIZE } from "./operators/OBJECT_ITEMSTACK_SIZE";
import { OPERATOR_OBJECT_ITEMSTACK_STORED_FE } from "./operators/OBJECT_ITEMSTACK_STORED_FE";
import { OPERATOR_OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK } from "./operators/OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK";
import { OPERATOR_OBJECT_ITEMSTACK_TAG_STACKS } from "./operators/OBJECT_ITEMSTACK_TAG_STACKS";
import { OPERATOR_OBJECT_ITEMSTACK_WITHSIZE } from "./operators/OBJECT_ITEMSTACK_WITHSIZE";
import { OPERATOR_OBJECT_PLAYER_TARGETBLOCK } from "./operators/OBJECT_PLAYER_TARGETBLOCK";
import { OPERATOR_OBJECT_PLAYER_TARGETENTITY } from "./operators/OBJECT_PLAYER_TARGETENTITY";
import { OPERATOR_OPERATOR_APPLY } from "./operators/OPERATOR_APPLY";
import { OPERATOR_OPERATOR_APPLY_0 } from "./operators/OPERATOR_APPLY_0";
import { OPERATOR_OPERATOR_APPLY_2 } from "./operators/OPERATOR_APPLY_2";
import { OPERATOR_OPERATOR_APPLY_3 } from "./operators/OPERATOR_APPLY_3";
import { OPERATOR_OPERATOR_APPLY_N } from "./operators/OPERATOR_APPLY_N";
import { OPERATOR_OPERATOR_BY_NAME } from "./operators/OPERATOR_BY_NAME";
import { OPERATOR_OPERATOR_CONJUNCTION } from "./operators/OPERATOR_CONJUNCTION";
import { OPERATOR_OPERATOR_DISJUNCTION } from "./operators/OPERATOR_DISJUNCTION";
import { OPERATOR_OPERATOR_FILTER } from "./operators/OPERATOR_FILTER";
import { OPERATOR_OPERATOR_FLIP } from "./operators/OPERATOR_FLIP";
import { OPERATOR_OPERATOR_MAP } from "./operators/OPERATOR_MAP";
import { OPERATOR_OPERATOR_NEGATION } from "./operators/OPERATOR_NEGATION";
import { OPERATOR_OPERATOR_PIPE } from "./operators/OPERATOR_PIPE";
import { OPERATOR_OPERATOR_PIPE2 } from "./operators/OPERATOR_PIPE2";
import { OPERATOR_OPERATOR_REDUCE } from "./operators/OPERATOR_REDUCE";
import { OPERATOR_OPERATOR_REDUCE1 } from "./operators/OPERATOR_REDUCE1";
import { OPERATOR_PARSE_BOOLEAN } from "./operators/PARSE_BOOLEAN";
import { OPERATOR_PARSE_DOUBLE } from "./operators/PARSE_DOUBLE";
import { OPERATOR_PARSE_INTEGER } from "./operators/PARSE_INTEGER";
import { OPERATOR_PARSE_LONG } from "./operators/PARSE_LONG";
import { OPERATOR_PARSE_NBT } from "./operators/PARSE_NBT";
import { OPERATOR_RECIPE_INPUT } from "./operators/RECIPE_INPUT";
import { OPERATOR_RECIPE_OUTPUT } from "./operators/RECIPE_OUTPUT";
import { OPERATOR_RECIPE_WITH_INPUT } from "./operators/RECIPE_WITH_INPUT";
import { OPERATOR_RECIPE_WITH_INPUT_OUTPUT } from "./operators/RECIPE_WITH_INPUT_OUTPUT";
import { OPERATOR_RECIPE_WITH_OUTPUT } from "./operators/RECIPE_WITH_OUTPUT";
import { OPERATOR_RELATIONAL_EQUALS } from "./operators/RELATIONAL_EQUALS";
import { OPERATOR_RELATIONAL_GE } from "./operators/RELATIONAL_GE";
import { OPERATOR_RELATIONAL_GT } from "./operators/RELATIONAL_GT";
import { OPERATOR_RELATIONAL_LE } from "./operators/RELATIONAL_LE";
import { OPERATOR_RELATIONAL_LT } from "./operators/RELATIONAL_LT";
import { OPERATOR_RELATIONAL_NOTEQUALS } from "./operators/RELATIONAL_NOTEQUALS";
import { OPERATOR_STRING_CONCAT } from "./operators/STRING_CONCAT";
import { OPERATOR_STRING_CONTAINS } from "./operators/STRING_CONTAINS";
import { OPERATOR_STRING_CONTAINS_REGEX } from "./operators/STRING_CONTAINS_REGEX";
import { OPERATOR_STRING_ENDS_WITH } from "./operators/STRING_ENDS_WITH";
import { OPERATOR_STRING_ERROR } from "./operators/STRING_ERROR";
import { OPERATOR_STRING_INDEX_OF } from "./operators/STRING_INDEX_OF";
import { OPERATOR_STRING_INDEX_OF_REGEX } from "./operators/STRING_INDEX_OF_REGEX";
import { OPERATOR_STRING_JOIN } from "./operators/STRING_JOIN";
import { OPERATOR_STRING_LENGTH } from "./operators/STRING_LENGTH";
import { OPERATOR_STRING_MATCHES_REGEX } from "./operators/STRING_MATCHES_REGEX";
import { OPERATOR_STRING_REGEX_GROUP } from "./operators/STRING_REGEX_GROUP";
import { OPERATOR_STRING_REGEX_GROUPS } from "./operators/STRING_REGEX_GROUPS";
import { OPERATOR_STRING_REGEX_SCAN } from "./operators/STRING_REGEX_SCAN";
import { OPERATOR_STRING_REPLACE } from "./operators/STRING_REPLACE";
import { OPERATOR_STRING_REPLACE_REGEX } from "./operators/STRING_REPLACE_REGEX";
import { OPERATOR_STRING_SPLIT_ON } from "./operators/STRING_SPLIT_ON";
import { OPERATOR_STRING_SPLIT_ON_REGEX } from "./operators/STRING_SPLIT_ON_REGEX";
import { OPERATOR_STRING_STARTS_WITH } from "./operators/STRING_STARTS_WITH";
import { OPERATOR_STRING_SUBSTRING } from "./operators/STRING_SUBSTRING";
import { OPERATOR_STRING_TAG } from "./operators/STRING_TAG";
import { OPERATOR_UNIQUELY_NAMED_UNIQUE_NAME } from "./operators/UNIQUELY_NAMED_UNIQUE_NAME";
import { OPERATOR_BINARY_RZSHIFT } from "./operators/BINARY_RZSHIFT";
import { OPERATOR_LIST_LAZYBUILT } from "./operators/LIST_LAZYBUILT";

let globalMap = new TypeMap();

let operatorRegistry = {
  LOGICAL_AND: new OPERATOR_LOGICAL_AND(globalMap),
  LOGICAL_OR: new OPERATOR_LOGICAL_OR(globalMap),
  LOGICAL_NOT: new OPERATOR_LOGICAL_NOT(globalMap),
  LOGICAL_NAND: new OPERATOR_LOGICAL_NAND(globalMap),
  LOGICAL_NOR: new OPERATOR_LOGICAL_NOR(globalMap),
  ARITHMETIC_ADDITION: new OPERATOR_ARITHMETIC_ADDITION(globalMap),
  ARITHMETIC_SUBTRACTION: new OPERATOR_ARITHMETIC_SUBTRACTION(globalMap),
  ARITHMETIC_MULTIPLICATION: new OPERATOR_ARITHMETIC_MULTIPLICATION(globalMap),
  ARITHMETIC_DIVISION: new OPERATOR_ARITHMETIC_DIVISION(globalMap),
  ARITHMETIC_MAXIMUM: new OPERATOR_ARITHMETIC_MAXIMUM(globalMap),
  ARITHMETIC_MINIMUM: new OPERATOR_ARITHMETIC_MINIMUM(globalMap),
  ARITHMETIC_INCREMENT: new OPERATOR_ARITHMETIC_INCREMENT(globalMap),
  ARITHMETIC_DECREMENT: new OPERATOR_ARITHMETIC_DECREMENT(globalMap),
  ARITHMETIC_MODULUS: new OPERATOR_ARITHMETIC_MODULUS(globalMap),
  DOUBLE_SQRT: new OPERATOR_DOUBLE_SQRT(globalMap),
  DOUBLE_POW: new OPERATOR_DOUBLE_POW(globalMap),
  RELATIONAL_EQUALS: new OPERATOR_RELATIONAL_EQUALS(globalMap),
  RELATIONAL_GT: new OPERATOR_RELATIONAL_GT(globalMap),
  RELATIONAL_LT: new OPERATOR_RELATIONAL_LT(globalMap),
  RELATIONAL_NOTEQUALS: new OPERATOR_RELATIONAL_NOTEQUALS(globalMap),
  RELATIONAL_GE: new OPERATOR_RELATIONAL_GE(globalMap),
  RELATIONAL_LE: new OPERATOR_RELATIONAL_LE(globalMap),
  BINARY_AND: new OPERATOR_BINARY_AND(globalMap),
  BINARY_OR: new OPERATOR_BINARY_OR(globalMap),
  BINARY_XOR: new OPERATOR_BINARY_XOR(globalMap),
  BINARY_COMPLEMENT: new OPERATOR_BINARY_COMPLEMENT(globalMap),
  BINARY_LSHIFT: new OPERATOR_BINARY_LSHIFT(globalMap),
  BINARY_RSHIFT: new OPERATOR_BINARY_RSHIFT(globalMap),
  BINARY_RZSHIFT: new OPERATOR_BINARY_RZSHIFT(globalMap),
  STRING_LENGTH: new OPERATOR_STRING_LENGTH(globalMap),
  STRING_CONCAT: new OPERATOR_STRING_CONCAT(globalMap),
  STRING_CONTAINS: new OPERATOR_STRING_CONTAINS(globalMap),
  STRING_CONTAINS_REGEX: new OPERATOR_STRING_CONTAINS_REGEX(globalMap),
  STRING_MATCHES_REGEX: new OPERATOR_STRING_MATCHES_REGEX(globalMap),
  STRING_INDEX_OF: new OPERATOR_STRING_INDEX_OF(globalMap),
  STRING_INDEX_OF_REGEX: new OPERATOR_STRING_INDEX_OF_REGEX(globalMap),
  STRING_STARTS_WITH: new OPERATOR_STRING_STARTS_WITH(globalMap),
  STRING_ENDS_WITH: new OPERATOR_STRING_ENDS_WITH(globalMap),
  STRING_SPLIT_ON: new OPERATOR_STRING_SPLIT_ON(globalMap),
  STRING_SPLIT_ON_REGEX: new OPERATOR_STRING_SPLIT_ON_REGEX(globalMap),
  STRING_SUBSTRING: new OPERATOR_STRING_SUBSTRING(globalMap),
  STRING_REGEX_GROUP: new OPERATOR_STRING_REGEX_GROUP(globalMap),
  STRING_REGEX_GROUPS: new OPERATOR_STRING_REGEX_GROUPS(globalMap),
  STRING_REGEX_SCAN: new OPERATOR_STRING_REGEX_SCAN(globalMap),
  STRING_REPLACE: new OPERATOR_STRING_REPLACE(globalMap),
  STRING_REPLACE_REGEX: new OPERATOR_STRING_REPLACE_REGEX(globalMap),
  STRING_JOIN: new OPERATOR_STRING_JOIN(globalMap),
  NAMED_NAME: new OPERATOR_NAMED_NAME(globalMap),
  UNIQUELY_NAMED_UNIQUE_NAME: new OPERATOR_UNIQUELY_NAMED_UNIQUE_NAME(
    globalMap
  ),
  STRING_ERROR: new OPERATOR_STRING_ERROR(globalMap),
  NUMBER_ROUND: new OPERATOR_NUMBER_ROUND(globalMap),
  NUMBER_CEIL: new OPERATOR_NUMBER_CEIL(globalMap),
  NUMBER_FLOOR: new OPERATOR_NUMBER_FLOOR(globalMap),
  NUMBER_COMPACT: new OPERATOR_NUMBER_COMPACT(globalMap),
  NULLABLE_ISNULL: new OPERATOR_NULLABLE_ISNULL(globalMap),
  NULLABLE_ISNOTNULL: new OPERATOR_NULLABLE_ISNOTNULL(globalMap),
  LIST_LENGTH: new OPERATOR_LIST_LENGTH(globalMap),
  LIST_EMPTY: new OPERATOR_LIST_EMPTY(globalMap),
  LIST_NOT_EMPTY: new OPERATOR_LIST_NOT_EMPTY(globalMap),
  LIST_ELEMENT: new OPERATOR_LIST_ELEMENT(globalMap),
  LIST_ELEMENT_DEFAULT: new OPERATOR_LIST_ELEMENT_DEFAULT(globalMap),
  LIST_CONTAINS: new OPERATOR_LIST_CONTAINS(globalMap),
  LIST_CONTAINS_PREDICATE: new OPERATOR_LIST_CONTAINS_PREDICATE(globalMap),
  LIST_COUNT: new OPERATOR_LIST_COUNT(globalMap),
  LIST_COUNT_PREDICATE: new OPERATOR_LIST_COUNT_PREDICATE(globalMap),
  LIST_APPEND: new OPERATOR_LIST_APPEND(globalMap),
  LIST_CONCAT: new OPERATOR_LIST_CONCAT(globalMap),
  LIST_LAZYBUILT: new OPERATOR_LIST_LAZYBUILT(globalMap),
  LIST_HEAD: new OPERATOR_LIST_HEAD(globalMap),
  LIST_TAIL: new OPERATOR_LIST_TAIL(globalMap),
  LIST_UNIQ_PREDICATE: new OPERATOR_LIST_UNIQ_PREDICATE(globalMap),
  LIST_UNIQ: new OPERATOR_LIST_UNIQ(globalMap),
  LIST_SLICE: new OPERATOR_LIST_SLICE(globalMap),
  LIST_INTERSECTION: new OPERATOR_LIST_INTERSECTION(globalMap),
  LIST_EQUALS_SET: new OPERATOR_LIST_EQUALS_SET(globalMap),
  LIST_EQUALS_MULTISET: new OPERATOR_LIST_EQUALS_MULTISET(globalMap),
  OBJECT_BLOCK_OPAQUE: new OPERATOR_OBJECT_BLOCK_OPAQUE(globalMap),
  OBJECT_BLOCK_ITEMSTACK: new OPERATOR_OBJECT_BLOCK_ITEMSTACK(globalMap),
  OBJECT_BLOCK_MODNAME: new OPERATOR_OBJECT_BLOCK_MODNAME(globalMap),
  OBJECT_BLOCK_BREAKSOUND: new OPERATOR_OBJECT_BLOCK_BREAKSOUND(globalMap),
  OBJECT_BLOCK_PLACESOUND: new OPERATOR_OBJECT_BLOCK_PLACESOUND(globalMap),
  OBJECT_BLOCK_STEPSOUND: new OPERATOR_OBJECT_BLOCK_STEPSOUND(globalMap),
  OBJECT_BLOCK_ISSHEARABLE: new OPERATOR_OBJECT_BLOCK_ISSHEARABLE(globalMap),
  OBJECT_BLOCK_PLANTAGE: new OPERATOR_OBJECT_BLOCK_PLANTAGE(globalMap),
  OBJECT_BLOCK_BY_NAME: new OPERATOR_OBJECT_BLOCK_BY_NAME(globalMap),
  OBJECT_BLOCK_PROPERTIES: new OPERATOR_OBJECT_BLOCK_PROPERTIES(globalMap),
  OBJECT_BLOCK_WITH_PROPERTIES: new OPERATOR_OBJECT_BLOCK_WITH_PROPERTIES(
    globalMap
  ),
  OBJECT_BLOCK_POSSIBLE_PROPERTIES:
    new OPERATOR_OBJECT_BLOCK_POSSIBLE_PROPERTIES(globalMap),
  OBJECT_BLOCK_TAG: new OPERATOR_OBJECT_BLOCK_TAG(globalMap),
  OBJECT_BLOCK_TAG_STACKS: new OPERATOR_OBJECT_BLOCK_TAG_STACKS(globalMap),
  OBJECT_ITEMSTACK_SIZE: new OPERATOR_OBJECT_ITEMSTACK_SIZE(globalMap),
  OBJECT_ITEMSTACK_MAXSIZE: new OPERATOR_OBJECT_ITEMSTACK_MAXSIZE(globalMap),
  OBJECT_ITEMSTACK_ISSTACKABLE: new OPERATOR_OBJECT_ITEMSTACK_ISSTACKABLE(
    globalMap
  ),
  OBJECT_ITEMSTACK_ISDAMAGEABLE: new OPERATOR_OBJECT_ITEMSTACK_ISDAMAGEABLE(
    globalMap
  ),
  OBJECT_ITEMSTACK_DAMAGE: new OPERATOR_OBJECT_ITEMSTACK_DAMAGE(globalMap),
  OBJECT_ITEMSTACK_MAXDAMAGE: new OPERATOR_OBJECT_ITEMSTACK_MAXDAMAGE(
    globalMap
  ),
  OBJECT_ITEMSTACK_ISENCHANTED: new OPERATOR_OBJECT_ITEMSTACK_ISENCHANTED(
    globalMap
  ),
  OBJECT_ITEMSTACK_ISENCHANTABLE: new OPERATOR_OBJECT_ITEMSTACK_ISENCHANTABLE(
    globalMap
  ),
  OBJECT_ITEMSTACK_REPAIRCOST: new OPERATOR_OBJECT_ITEMSTACK_REPAIRCOST(
    globalMap
  ),
  OBJECT_ITEMSTACK_RARITY: new OPERATOR_OBJECT_ITEMSTACK_RARITY(globalMap),
  OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK:
    new OPERATOR_OBJECT_ITEMSTACK_STRENGTH_VS_BLOCK(globalMap),
  OBJECT_ITEMSTACK_CANHARVESTBLOCK:
    new OPERATOR_OBJECT_ITEMSTACK_CANHARVESTBLOCK(globalMap),
  OBJECT_ITEMSTACK_BLOCK: new OPERATOR_OBJECT_ITEMSTACK_BLOCK(globalMap),
  OBJECT_ITEMSTACK_ISFLUIDSTACK: new OPERATOR_OBJECT_ITEMSTACK_ISFLUIDSTACK(
    globalMap
  ),
  OBJECT_ITEMSTACK_FLUIDSTACK: new OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACK(
    globalMap
  ),
  OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY:
    new OPERATOR_OBJECT_ITEMSTACK_FLUIDSTACKCAPACITY(globalMap),
  OBJECT_ITEMSTACK_ISDATAEQUAL: new OPERATOR_OBJECT_ITEMSTACK_ISDATAEQUAL(
    globalMap
  ),
  OBJECT_ITEMSTACK_ISITEMEQUALNODATA:
    new OPERATOR_OBJECT_ITEMSTACK_ISITEMEQUALNODATA(globalMap),
  OBJECT_ITEMSTACK_ISRAWITEMEQUAL: new OPERATOR_OBJECT_ITEMSTACK_ISRAWITEMEQUAL(
    globalMap
  ),
  OBJECT_ITEMSTACK_MODNAME: new OPERATOR_OBJECT_ITEMSTACK_MODNAME(globalMap),
  OBJECT_ITEMSTACK_FUELBURNTIME: new OPERATOR_OBJECT_ITEMSTACK_FUELBURNTIME(
    globalMap
  ),
  ITEMSTACK_CANBURN: new OPERATOR_ITEMSTACK_CANBURN(globalMap),
  ITEMSTACK_TAG: new OPERATOR_ITEMSTACK_TAG(globalMap),
  STRING_TAG: new OPERATOR_STRING_TAG(globalMap),
  OBJECT_ITEMSTACK_TAG_STACKS: new OPERATOR_OBJECT_ITEMSTACK_TAG_STACKS(
    globalMap
  ),
  OBJECT_ITEMSTACK_WITHSIZE: new OPERATOR_OBJECT_ITEMSTACK_WITHSIZE(globalMap),
  ITEMSTACK_ISFECONTAINER: new OPERATOR_ITEMSTACK_ISFECONTAINER(globalMap),
  OBJECT_ITEMSTACK_STORED_FE: new OPERATOR_OBJECT_ITEMSTACK_STORED_FE(
    globalMap
  ),
  OBJECT_ITEMSTACK_FE_CAPACITY: new OPERATOR_OBJECT_ITEMSTACK_FE_CAPACITY(
    globalMap
  ),
  OBJECT_ITEMSTACK_HASINVENTORY: new OPERATOR_OBJECT_ITEMSTACK_HASINVENTORY(
    globalMap
  ),
  OBJECT_ITEMSTACK_INVENTORYSIZE: new OPERATOR_OBJECT_ITEMSTACK_INVENTORYSIZE(
    globalMap
  ),
  OBJECT_ITEMSTACK_INVENTORY: new OPERATOR_OBJECT_ITEMSTACK_INVENTORY(
    globalMap
  ),
  ITEMSTACK_ITEMBYNAME: new OPERATOR_ITEMSTACK_ITEMBYNAME(globalMap),
  ITEMSTACK_ITEMLISTCOUNT: new OPERATOR_ITEMSTACK_ITEMLISTCOUNT(globalMap),
  OBJECT_ITEMSTACK_NBT: new OPERATOR_OBJECT_ITEMSTACK_NBT(globalMap),
  OBJECT_ITEMSTACK_HASNBT: new OPERATOR_OBJECT_ITEMSTACK_HASNBT(globalMap),
  OBJECT_ITEMSTACK_DATA_KEYS: new OPERATOR_OBJECT_ITEMSTACK_DATA_KEYS(
    globalMap
  ),
  ITEMSTACK_DATAVALUE: new OPERATOR_ITEMSTACK_DATAVALUE(globalMap),
  ITEMSTACK_WITHDATA: new OPERATOR_ITEMSTACK_WITHDATA(globalMap),
  ITEMSTACK_TOOLTIP: new OPERATOR_ITEMSTACK_TOOLTIP(globalMap),
  OBJECT_ENTITY_ENTITYITEMTOOLTIP: new OPERATOR_OBJECT_ENTITY_ENTITYITEMTOOLTIP(
    globalMap
  ),
  OBJECT_ENTITY_ISMOB: new OPERATOR_OBJECT_ENTITY_ISMOB(globalMap),
  OBJECT_ENTITY_ISANIMAL: new OPERATOR_OBJECT_ENTITY_ISANIMAL(globalMap),
  OBJECT_ENTITY_ISITEM: new OPERATOR_OBJECT_ENTITY_ISITEM(globalMap),
  OBJECT_ENTITY_ISPLAYER: new OPERATOR_OBJECT_ENTITY_ISPLAYER(globalMap),
  ENTITY_ISMINECART: new OPERATOR_ENTITY_ISMINECART(globalMap),
  ENTITY_ITEM: new OPERATOR_ENTITY_ITEM(globalMap),
  ENTITY_HEALTH: new OPERATOR_ENTITY_HEALTH(globalMap),
  ENTITY_WIDTH: new OPERATOR_ENTITY_WIDTH(globalMap),
  OBJECT_ENTITY_WIDTH: new OPERATOR_OBJECT_ENTITY_WIDTH(globalMap),
  OBJECT_ENTITY_HEIGHT: new OPERATOR_OBJECT_ENTITY_HEIGHT(globalMap),
  OBJECT_ENTITY_ISBURNING: new OPERATOR_OBJECT_ENTITY_ISBURNING(globalMap),
  OBJECT_ENTITY_ISWET: new OPERATOR_OBJECT_ENTITY_ISWET(globalMap),
  OBJECT_ENTITY_ISCROUCHING: new OPERATOR_OBJECT_ENTITY_ISCROUCHING(globalMap),
  OBJECT_ENTITY_ISEATING: new OPERATOR_OBJECT_ENTITY_ISEATING(globalMap),
  ENTITY_ARMORINVENTORY: new OPERATOR_ENTITY_ARMORINVENTORY(globalMap),
  OBJECT_ENTITY_INVENTORY: new OPERATOR_OBJECT_ENTITY_INVENTORY(globalMap),
  OBJECT_ENTITY_MODNAME: new OPERATOR_OBJECT_ENTITY_MODNAME(globalMap),
  OBJECT_PLAYER_TARGETBLOCK: new OPERATOR_OBJECT_PLAYER_TARGETBLOCK(globalMap),
  OBJECT_PLAYER_TARGETENTITY: new OPERATOR_OBJECT_PLAYER_TARGETENTITY(
    globalMap
  ),
  ENTITY_HASGUIOPEN: new OPERATOR_ENTITY_HASGUIOPEN(globalMap),
  ENTITY_HELDITEM: new OPERATOR_ENTITY_HELDITEM(globalMap),
  ENTITY_HELDITEMOFFHAND: new OPERATOR_ENTITY_HELDITEMOFFHAND(globalMap),
  OBJECT_ENTITY_MOUNTED: new OPERATOR_OBJECT_ENTITY_MOUNTED(globalMap),
  OBJECT_ITEMFRAME_CONTENTS: new OPERATOR_OBJECT_ITEMFRAME_CONTENTS(globalMap),
  OBJECT_ITEMFRAME_ROTATION: new OPERATOR_OBJECT_ITEMFRAME_ROTATION(globalMap),
  OBJECT_ENTITY_HURTSOUND: new OPERATOR_OBJECT_ENTITY_HURTSOUND(globalMap),
  OBJECT_ENTITY_DEATHSOUND: new OPERATOR_OBJECT_ENTITY_DEATHSOUND(globalMap),
  OBJECT_ENTITY_AGE: new OPERATOR_OBJECT_ENTITY_AGE(globalMap),
  OBJECT_ENTITY_ISCHILD: new OPERATOR_OBJECT_ENTITY_ISCHILD(globalMap),
  OBJECT_ENTITY_CANBREED: new OPERATOR_OBJECT_ENTITY_CANBREED(globalMap),
  OBJECT_ENTITY_ISINLOVE: new OPERATOR_OBJECT_ENTITY_ISINLOVE(globalMap),
  OBJECT_ENTITY_CANBREEDWITH: new OPERATOR_OBJECT_ENTITY_CANBREEDWITH(
    globalMap
  ),
  OBJECT_ENTITY_ISSHEARABLE: new OPERATOR_OBJECT_ENTITY_ISSHEARABLE(globalMap),
  OBJECT_ENTITY_NBT: new OPERATOR_OBJECT_ENTITY_NBT(globalMap),
  OBJECT_ENTITY_TYPE: new OPERATOR_OBJECT_ENTITY_TYPE(globalMap),
  OBJECT_ENTITY_ITEMS: new OPERATOR_OBJECT_ENTITY_ITEMS(globalMap),
  OBJECT_ENTITY_FLUIDS: new OPERATOR_OBJECT_ENTITY_FLUIDS(globalMap),
  OBJECT_ENTITY_ENERGY_STORED: new OPERATOR_OBJECT_ENTITY_ENERGY_STORED(
    globalMap
  ),
  OBJECT_ENTITY_ENERGY_CAPACITY: new OPERATOR_OBJECT_ENTITY_ENERGY_CAPACITY(
    globalMap
  ),
  OBJECT_FLUIDSTACK_AMOUNT: new OPERATOR_OBJECT_FLUIDSTACK_AMOUNT(globalMap),
  OBJECT_FLUIDSTACK_BLOCK: new OPERATOR_OBJECT_FLUIDSTACK_BLOCK(globalMap),
  OBJECT_FLUIDSTACK_LIGHT_LEVEL: new OPERATOR_OBJECT_FLUIDSTACK_LIGHT_LEVEL(
    globalMap
  ),
  OBJECT_FLUIDSTACK_DENSITY: new OPERATOR_OBJECT_FLUIDSTACK_DENSITY(globalMap),
  OBJECT_FLUIDSTACK_TEMPERATURE: new OPERATOR_OBJECT_FLUIDSTACK_TEMPERATURE(
    globalMap
  ),
  OBJECT_FLUIDSTACK_VISCOSITY: new OPERATOR_OBJECT_FLUIDSTACK_VISCOSITY(
    globalMap
  ),
  OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR:
    new OPERATOR_OBJECT_FLUIDSTACK_IS_LIGHTER_THAN_AIR(globalMap),
  OBJECT_FLUIDSTACK_RARITY: new OPERATOR_OBJECT_FLUIDSTACK_RARITY(globalMap),
  OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY:
    new OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_EMPTY(globalMap),
  OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE:
    new OPERATOR_OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE(globalMap),
  OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL:
    new OPERATOR_OBJECT_FLUIDSTACK_SOUND_BUCKET_FILL(globalMap),
  OBJECT_FLUIDSTACK_BUCKET: new OPERATOR_OBJECT_FLUIDSTACK_BUCKET(globalMap),
  OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL:
    new OPERATOR_OBJECT_FLUIDSTACK_ISRAWFLUIDEQUAL(globalMap),
  OBJECT_FLUIDSTACK_MODNAME: new OPERATOR_OBJECT_FLUIDSTACK_MODNAME(globalMap),
  OBJECT_FLUIDSTACK_DATA: new OPERATOR_OBJECT_FLUIDSTACK_DATA(globalMap),
  OBJECT_FLUIDSTACK_WITH_AMOUNT: new OPERATOR_OBJECT_FLUIDSTACK_WITH_AMOUNT(
    globalMap
  ),
  OBJECT_FLUIDSTACK_DATAKEYS: new OPERATOR_OBJECT_FLUIDSTACK_DATAKEYS(
    globalMap
  ),
  OBJECT_FLUIDSTACK_DATA_VALUE: new OPERATOR_OBJECT_FLUIDSTACK_DATA_VALUE(
    globalMap
  ),
  OBJECT_FLUIDSTACK_WITH_DATA: new OPERATOR_OBJECT_FLUIDSTACK_WITH_DATA(
    globalMap
  ),
  OBJECT_FLUIDSTACK_BY_NAME: new OPERATOR_OBJECT_FLUIDSTACK_BY_NAME(globalMap),
  OBJECT_FLUIDSTACK_TAG: new OPERATOR_OBJECT_FLUIDSTACK_TAG(globalMap),
  OBJECT_FLUIDSTACK_TAG_STACKS: new OPERATOR_OBJECT_FLUIDSTACK_TAG_STACKS(
    globalMap
  ),
  OPERATOR_APPLY: new OPERATOR_OPERATOR_APPLY(globalMap),
  OPERATOR_APPLY_2: new OPERATOR_OPERATOR_APPLY_2(globalMap),
  OPERATOR_APPLY_3: new OPERATOR_OPERATOR_APPLY_3(globalMap),
  OPERATOR_APPLY_N: new OPERATOR_OPERATOR_APPLY_N(globalMap),
  OPERATOR_APPLY_0: new OPERATOR_OPERATOR_APPLY_0(globalMap),
  OPERATOR_MAP: new OPERATOR_OPERATOR_MAP(globalMap),
  OPERATOR_FILTER: new OPERATOR_OPERATOR_FILTER(globalMap),
  OPERATOR_CONJUNCTION: new OPERATOR_OPERATOR_CONJUNCTION(globalMap),
  OPERATOR_DISJUNCTION: new OPERATOR_OPERATOR_DISJUNCTION(globalMap),
  OPERATOR_NEGATION: new OPERATOR_OPERATOR_NEGATION(globalMap),
  OPERATOR_PIPE: new OPERATOR_OPERATOR_PIPE(globalMap),
  OPERATOR_PIPE2: new OPERATOR_OPERATOR_PIPE2(globalMap),
  OPERATOR_FLIP: new OPERATOR_OPERATOR_FLIP(globalMap),
  OPERATOR_REDUCE: new OPERATOR_OPERATOR_REDUCE(globalMap),
  OPERATOR_REDUCE1: new OPERATOR_OPERATOR_REDUCE1(globalMap),
  OPERATOR_BY_NAME: new OPERATOR_OPERATOR_BY_NAME(globalMap),
  NBT_COMPOUND_SIZE: new OPERATOR_NBT_COMPOUND_SIZE(globalMap),
  NBT_COMPOUND_KEYS: new OPERATOR_NBT_COMPOUND_KEYS(globalMap),
  NBT_COMPOUND_HASKEY: new OPERATOR_NBT_COMPOUND_HASKEY(globalMap),
  NBT_COMPOUND_VALUE_TYPE: new OPERATOR_NBT_COMPOUND_VALUE_TYPE(globalMap),
  NBT_COMPOUND_VALUE_TAG: new OPERATOR_NBT_COMPOUND_VALUE_TAG(globalMap),
  NBT_COMPOUND_VALUE_BOOLEAN: new OPERATOR_NBT_COMPOUND_VALUE_BOOLEAN(
    globalMap
  ),
  NBT_COMPOUND_VALUE_INTEGER: new OPERATOR_NBT_COMPOUND_VALUE_INTEGER(
    globalMap
  ),
  NBT_COMPOUND_VALUE_LONG: new OPERATOR_NBT_COMPOUND_VALUE_LONG(globalMap),
  NBT_COMPOUND_VALUE_DOUBLE: new OPERATOR_NBT_COMPOUND_VALUE_DOUBLE(globalMap),
  NBT_COMPOUND_VALUE_STRING: new OPERATOR_NBT_COMPOUND_VALUE_STRING(globalMap),
  NBT_COMPOUND_VALUE_COMPOUND: new OPERATOR_NBT_COMPOUND_VALUE_COMPOUND(
    globalMap
  ),
  NBT_COMPOUND_VALUE_LIST_TAG: new OPERATOR_NBT_COMPOUND_VALUE_LIST_TAG(
    globalMap
  ),
  NBT_COMPOUND_VALUE_LIST_BYTE: new OPERATOR_NBT_COMPOUND_VALUE_LIST_BYTE(
    globalMap
  ),
  NBT_COMPOUND_VALUE_LIST_INT: new OPERATOR_NBT_COMPOUND_VALUE_LIST_INT(
    globalMap
  ),
  NBT_COMPOUND_VALUE_LIST_LONG: new OPERATOR_NBT_COMPOUND_VALUE_LIST_LONG(
    globalMap
  ),
  NBT_COMPOUND_WITHOUT: new OPERATOR_NBT_COMPOUND_WITHOUT(globalMap),
  NBT_COMPOUND_WITH_BOOLEAN: new OPERATOR_NBT_COMPOUND_WITH_BOOLEAN(globalMap),
  NBT_COMPOUND_WITH_SHORT: new OPERATOR_NBT_COMPOUND_WITH_SHORT(globalMap),
  NBT_COMPOUND_WITH_INTEGER: new OPERATOR_NBT_COMPOUND_WITH_INTEGER(globalMap),
  NBT_COMPOUND_WITH_LONG: new OPERATOR_NBT_COMPOUND_WITH_LONG(globalMap),
  NBT_COMPOUND_WITH_DOUBLE: new OPERATOR_NBT_COMPOUND_WITH_DOUBLE(globalMap),
  NBT_COMPOUND_WITH_FLOAT: new OPERATOR_NBT_COMPOUND_WITH_FLOAT(globalMap),
  NBT_COMPOUND_WITH_STRING: new OPERATOR_NBT_COMPOUND_WITH_STRING(globalMap),
  NBT_COMPOUND_WITH_COMPOUND: new OPERATOR_NBT_COMPOUND_WITH_COMPOUND(
    globalMap
  ),
  NBT_COMPOUND_WITH_LIST_TAG: new OPERATOR_NBT_COMPOUND_WITH_LIST_TAG(
    globalMap
  ),
  NBT_COMPOUND_WITH_LIST_BYTE: new OPERATOR_NBT_COMPOUND_WITH_LIST_BYTE(
    globalMap
  ),
  NBT_COMPOUND_WITH_LIST_INT: new OPERATOR_NBT_COMPOUND_WITH_LIST_INT(
    globalMap
  ),
  NBT_COMPOUND_WITH_LIST_LONG: new OPERATOR_NBT_COMPOUND_WITH_LIST_LONG(
    globalMap
  ),
  NBT_COMPOUND_SUBSET: new OPERATOR_NBT_COMPOUND_SUBSET(globalMap),
  NBT_COMPOUND_UNION: new OPERATOR_NBT_COMPOUND_UNION(globalMap),
  NBT_COMPOUND_INTERSECTION: new OPERATOR_NBT_COMPOUND_INTERSECTION(globalMap),
  NBT_COMPOUND_MINUS: new OPERATOR_NBT_COMPOUND_MINUS(globalMap),
  NBT_AS_BOOLEAN: new OPERATOR_NBT_AS_BOOLEAN(globalMap),
  NBT_AS_BYTE: new OPERATOR_NBT_AS_BYTE(globalMap),
  NBT_AS_SHORT: new OPERATOR_NBT_AS_SHORT(globalMap),
  NBT_AS_INT: new OPERATOR_NBT_AS_INT(globalMap),
  NBT_AS_LONG: new OPERATOR_NBT_AS_LONG(globalMap),
  NBT_AS_DOUBLE: new OPERATOR_NBT_AS_DOUBLE(globalMap),
  NBT_AS_FLOAT: new OPERATOR_NBT_AS_FLOAT(globalMap),
  NBT_AS_STRING: new OPERATOR_NBT_AS_STRING(globalMap),
  NBT_AS_TAG_LIST: new OPERATOR_NBT_AS_TAG_LIST(globalMap),
  NBT_AS_BYTE_LIST: new OPERATOR_NBT_AS_BYTE_LIST(globalMap),
  NBT_AS_INT_LIST: new OPERATOR_NBT_AS_INT_LIST(globalMap),
  NBT_AS_LONG_LIST: new OPERATOR_NBT_AS_LONG_LIST(globalMap),
  NBT_FROM_BOOLEAN: new OPERATOR_NBT_FROM_BOOLEAN(globalMap),
  NBT_FROM_SHORT: new OPERATOR_NBT_FROM_SHORT(globalMap),
  NBT_FROM_BYTE: new OPERATOR_NBT_FROM_BYTE(globalMap),
  NBT_FROM_INT: new OPERATOR_NBT_FROM_INT(globalMap),
  NBT_FROM_LONG: new OPERATOR_NBT_FROM_LONG(globalMap),
  NBT_FROM_DOUBLE: new OPERATOR_NBT_FROM_DOUBLE(globalMap),
  NBT_FROM_FLOAT: new OPERATOR_NBT_FROM_FLOAT(globalMap),
  NBT_FROM_STRING: new OPERATOR_NBT_FROM_STRING(globalMap),
  NBT_FROM_TAG_LIST: new OPERATOR_NBT_FROM_TAG_LIST(globalMap),
  NBT_FROM_BYTE_LIST: new OPERATOR_NBT_FROM_BYTE_LIST(globalMap),
  NBT_FROM_INT_LIST: new OPERATOR_NBT_FROM_INT_LIST(globalMap),
  NBT_FROM_LONG_LIST: new OPERATOR_NBT_FROM_LONG_LIST(globalMap),
  NBT_PATH_MATCH_FIRST: new OPERATOR_NBT_PATH_MATCH_FIRST(globalMap),
  NBT_PATH_MATCH_ALL: new OPERATOR_NBT_PATH_MATCH_ALL(globalMap),
  NBT_PATH_TEST: new OPERATOR_NBT_PATH_TEST(globalMap),
  INGREDIENTS_ITEMS: new OPERATOR_INGREDIENTS_ITEMS(globalMap),
  INGREDIENTS_FLUIDS: new OPERATOR_INGREDIENTS_FLUIDS(globalMap),
  INGREDIENTS_ENERGIES: new OPERATOR_INGREDIENTS_ENERGIES(globalMap),
  INGREDIENTS_WITH_ITEM: new OPERATOR_INGREDIENTS_WITH_ITEM(globalMap),
  INGREDIENTS_WITH_FLUID: new OPERATOR_INGREDIENTS_WITH_FLUID(globalMap),
  INGREDIENTS_WITH_ENERGY: new OPERATOR_INGREDIENTS_WITH_ENERGY(globalMap),
  INGREDIENTS_WITH_ITEMS: new OPERATOR_INGREDIENTS_WITH_ITEMS(globalMap),
  INGREDIENTS_WITH_FLUIDS: new OPERATOR_INGREDIENTS_WITH_FLUIDS(globalMap),
  INGREDIENTS_WITH_ENERGIES: new OPERATOR_INGREDIENTS_WITH_ENERGIES(globalMap),
  RECIPE_INPUT: new OPERATOR_RECIPE_INPUT(globalMap),
  RECIPE_OUTPUT: new OPERATOR_RECIPE_OUTPUT(globalMap),
  RECIPE_WITH_INPUT: new OPERATOR_RECIPE_WITH_INPUT(globalMap),
  RECIPE_WITH_OUTPUT: new OPERATOR_RECIPE_WITH_OUTPUT(globalMap),
  RECIPE_WITH_INPUT_OUTPUT: new OPERATOR_RECIPE_WITH_INPUT_OUTPUT(globalMap),
  PARSE_BOOLEAN: new OPERATOR_PARSE_BOOLEAN(globalMap),
  PARSE_DOUBLE: new OPERATOR_PARSE_DOUBLE(globalMap),
  PARSE_INTEGER: new OPERATOR_PARSE_INTEGER(globalMap),
  PARSE_LONG: new OPERATOR_PARSE_LONG(globalMap),
  PARSE_NBT: new OPERATOR_PARSE_NBT(globalMap),
  GENERAL_CHOICE: new OPERATOR_GENERAL_CHOICE(globalMap),
  GENERAL_IDENTITY: new OPERATOR_GENERAL_IDENTITY(globalMap),
  GENERAL_CONSTANT: new OPERATOR_GENERAL_CONSTANT(globalMap),
  INTEGER_TO_DOUBLE: new OPERATOR_INTEGER_TO_DOUBLE(globalMap),
  INTEGER_TO_LONG: new OPERATOR_INTEGER_TO_LONG(globalMap),
  DOUBLE_TO_INTEGER: new OPERATOR_DOUBLE_TO_INTEGER(globalMap),
  DOUBLE_TO_LONG: new OPERATOR_DOUBLE_TO_LONG(globalMap),
  LONG_TO_INTEGER: new OPERATOR_LONG_TO_INTEGER(globalMap),
  LONG_TO_DOUBLE: new OPERATOR_LONG_TO_DOUBLE(globalMap),
} as const;

export { operatorRegistry };
